import {
  NEWSLETTER_GDPR_MODAL_INTRO,
  NEWSLETTER_GDPR_MODAL_TITLE,
  NEWSLETTER_GDPR_SECTIONS
} from '@/lib/content/newsletter-gdpr';

export const EVENT_REGISTRATION_GDPR_LEGAL_TEXT_VERSION = 'event-registration-gdpr-v1';
export const EVENT_REGISTRATION_GDPR_MODAL_TITLE = NEWSLETTER_GDPR_MODAL_TITLE;
export const EVENT_REGISTRATION_GDPR_MODAL_INTRO = NEWSLETTER_GDPR_MODAL_INTRO;
export const EVENT_REGISTRATION_GDPR_SECTIONS = NEWSLETTER_GDPR_SECTIONS;
