- targets:
  - https://academicsstand.org
  - https://designer.velvetdinosaur.com
  - https://journalasap.org
  - https://journal.ontourism.academy
  - https://manage.velvetdinosaur.com
  - https://ontourism.academy
  - https://pyanal.velvetdinosaur.com
  - https://remake.risingdustadventures.com
  - https://risingdustadventures.com
  - https://scholardemia.com
  - https://space.scholardemia.com
  - https://thebrave.online
  - https://theme.velvetdinosaur.com
  - https://velvetdinosaur.com
  - https://www.academicsstand.org
  - https://www.journalasap.org
  - https://www.journal.ontourism.academy
  - https://www.ontourism.academy
  - https://www.risingdustadventures.com
  - https://www.scholardemia.com
  - https://www.thebrave.online
  - https://www.velvetdinosaur.com
