// Site-specific editor field vocabulary. Entries here win over the base
// dictionary in puck/field-vocabulary.ts. Keyed by lowercased prop name.
// This file is owned by the site and never overwritten by sync:editor.

import type { FieldVocabEntry } from '@/puck/field-vocabulary';

export const SITE_FIELD_VOCABULARY: Record<string, FieldVocabEntry> = {
  badgelabel: { label: 'Badge text', help: 'Text shown on the badge.' },
  baseline: { label: 'Pricing baseline', help: 'The baseline package shown in the pricing section.' },
  baselineitems: { label: 'Baseline items', help: 'The baseline entries shown. Add, remove, or reorder them.' },
  baselinelabel: { label: 'Baseline text', help: 'Text shown on the baseline.' },
  baselineprice: { label: 'Baseline price', help: 'The starting price shown for the baseline package.' },
  benefits: { label: 'Benefits', help: 'The benefits shown in this section. Add, remove, or reorder them.' },
  bottomlinks: { label: 'Bottom links', help: 'The bottom links shown in this section. Add, remove, or reorder them.' },
  buttons: { label: 'Buttons', help: 'The buttons shown in this section. Add, remove, or reorder them.' },
  buttontext: { label: 'Button text', help: 'Text shown on the button.' },
  buttonurl: { label: 'Button link', help: 'Where the button takes visitors when clicked.' },
  callouts: { label: 'Callouts', help: 'The callouts shown in this section. Add, remove, or reorder them.' },
  clarifiers: { label: 'Clarifiers', help: 'The clarifiers shown in this section. Add, remove, or reorder them.' },
  clearfilterslabel: { label: 'Clear filters text', help: 'Text shown on the clear filters.' },
  company: { label: 'Company name', help: 'The company name as it should appear.' },
  complexitynote: { label: 'Complexity note', help: 'Small print shown with the complexity.' },
  contactbuttons: { label: 'Contact buttons', help: 'The contact buttons shown in this section. Add, remove, or reorder them.' },
  contactdetails: { label: 'Contact details', help: 'The contact details shown in this section. Add, remove, or reorder them.' },
  contactdetailstitle: { label: 'Contact details heading', help: 'Heading shown for the contact details.' },
  contactinfo: { label: 'Contact details', help: 'The contact details shown in this section.' },
  contactitems: { label: 'Contact items', help: 'The contact entries shown. Add, remove, or reorder them.' },
  contactoptions: { label: 'Contact options', help: 'The contact options shown in this section. Add, remove, or reorder them.' },
  contentclassname: { label: 'Content custom class', help: 'Advanced: custom CSS class names for the content area.' },
  ctasublabel: { label: 'Button sub text', help: 'Text shown on the button sub.' },
  ctatooltiplabel: { label: 'Button tooltip text', help: 'Text shown on the button tooltip.' },
  defaultvisible: { label: 'Visible by default', help: 'Turn on to show this as soon as the page loads.' },
  detaillabels: { label: 'Detail labels', help: 'The detail labels shown in this section. Add, remove, or reorder them.' },
  dismisslabel: { label: 'Dismiss text', help: 'Text shown on the dismiss.' },
  editableheading: { label: 'Editable heading', help: 'Heading shown for the editable.' },
  editableitems: { label: 'Editable items', help: 'The editable entries shown. Add, remove, or reorder them.' },
  emptymessage: { label: 'Empty-state message', help: 'Text shown when there is nothing to display yet.' },
  enabled: { label: 'Enabled', help: 'Turn this section on or off.' },
  expertisetitle: { label: 'Expertise heading', help: 'Heading shown for the expertise.' },
  extraheading: { label: 'Extra heading', help: 'Heading shown for the extra.' },
  extralistitems: { label: 'Extra list items', help: 'The extra list entries shown. Add, remove, or reorder them.' },
  extraparagraphs: { label: 'Extra paragraphs', help: 'The extra paragraphs shown in this section. Add, remove, or reorder them.' },
  factors: { label: 'Factors', help: 'The factors shown in this section. Add, remove, or reorder them.' },
  factorstitle: { label: 'Factors heading', help: 'Heading shown for the factors.' },
  faqslabel: { label: 'FAQs text', help: 'Text shown on the FAQs.' },
  featured: { label: 'Featured', help: 'Turn on to highlight this item as featured.' },
  fields: { label: 'Fields', help: 'The fields shown in this section. Add, remove, or reorder them.' },
  firstname: { label: 'First name', help: 'The first name shown or used by this section.' },
  formerrormessage: { label: 'Form error message', help: 'Text shown if the form fails to send.' },
  formlabels: { label: 'Form labels', help: 'The form labels shown in this section. Add, remove, or reorder them.' },
  formsuccessmessage: { label: 'Form success message', help: 'Text shown after the form is sent successfully.' },
  githubrepourl: { label: 'Github repo link', help: 'Where the github repo takes visitors when clicked.' },
  googlereviewsurl: { label: 'Google reviews link', help: 'Where the google reviews takes visitors when clicked.' },
  headericonalt: { label: 'Header icon image description', help: 'Describes the header icon image for screen readers and search engines.' },
  headericonsrc: { label: 'Header icon image', help: 'The image shown for the header icon. Choose from the media library or upload one.' },
  hostingcards: { label: 'Hosting cards', help: 'The hosting cards shown in this section. Add, remove, or reorder them.' },
  hostingdetails: { label: 'Hosting details', help: 'The hosting details shown in this section. Add, remove, or reorder them.' },
  hostingheading: { label: 'Hosting heading', help: 'Heading shown for the hosting.' },
  hostingitems: { label: 'Hosting items', help: 'The hosting entries shown. Add, remove, or reorder them.' },
  hostingnotes: { label: 'Hosting notes', help: 'The hosting notes shown in this section. Add, remove, or reorder them.' },
  hostingtitle: { label: 'Hosting heading', help: 'Heading shown for the hosting.' },
  icon: { label: 'Icon', help: 'The small symbol shown with this item.' },
  includes: { label: 'Includes', help: 'The includes shown in this section. Add, remove, or reorder them.' },
  includesheading: { label: 'Includes heading', help: 'Heading shown for the includes.' },
  includestitle: { label: 'Includes heading', help: 'Heading shown for the includes.' },
  inputplaceholder: { label: 'Input hint text', help: 'Grey hint text shown in the input box before anyone types.' },
  introparagraphs: { label: 'Intro paragraphs', help: 'The intro paragraphs shown in this section. Add, remove, or reorder them.' },
  lastname: { label: 'Last name', help: 'The last name shown or used by this section.' },
  linklabel: { label: 'Link text', help: 'Text shown on the link.' },
  linktext: { label: 'Link text', help: 'Text shown on the link.' },
  linkurl: { label: 'Link', help: 'Where the link takes visitors when clicked.' },
  listgroups: { label: 'List groups', help: 'The list groups shown in this section. Add, remove, or reorder them.' },
  logo: { label: 'Logo', help: 'The logo shown. Choose from the media library or upload one.' },
  menu: { label: 'Menu links', help: 'The links shown in the menu.' },
  menuitems: { label: 'Menu items', help: 'The menu entries shown. Add, remove, or reorder them.' },
  metaitems: { label: 'Meta items', help: 'The meta entries shown. Add, remove, or reorder them.' },
  metaline: { label: 'Small detail line', help: 'Small line of extra detail shown with the heading.' },
  mobiletitle: { label: 'Mobile heading', help: 'Heading shown for the mobile.' },
  navigation: { label: 'Navigation links', help: 'The links shown in the navigation.' },
  note: { label: 'Note', help: 'Small print shown with this section.' },
  notes: { label: 'Notes', help: 'The notes shown in this section. Add, remove, or reorder them.' },
  objectfields: { label: 'Object fields', help: 'The object fields shown in this section. Add, remove, or reorder them.' },
  officehours: { label: 'Office hours', help: 'The office hours shown in this section. Add, remove, or reorder them.' },
  officehourstitle: { label: 'Office hours heading', help: 'Heading shown for the office hours.' },
  ongoinglabel: { label: 'Ongoing text', help: 'Text shown on the ongoing.' },
  optionallabel: { label: 'Optional text', help: 'Text shown on the optional.' },
  outcomelabel: { label: 'Outcome text', help: 'Text shown on the outcome.' },
  outroparagraphs: { label: 'Outro paragraphs', help: 'The outro paragraphs shown in this section. Add, remove, or reorder them.' },
  paddingclassname: { label: 'Spacing custom class', help: 'Advanced: custom CSS class names controlling spacing.' },
  phonelabel: { label: 'Phone text', help: 'Text shown on the phone.' },
  portfoliomagazinearialabel: { label: 'Portfolio magazine aria text', help: 'Text shown on the portfolio magazine aria.' },
  portfoliomagazinelabel: { label: 'Portfolio magazine text', help: 'Text shown on the portfolio magazine.' },
  portfoliostackarialabel: { label: 'Portfolio stack aria text', help: 'Text shown on the portfolio stack aria.' },
  portfoliostacklabel: { label: 'Portfolio stack text', help: 'Text shown on the portfolio stack.' },
  preview: { label: 'Preview', help: 'The preview content shown for this item.' },
  primaryaction: { label: 'Main button', help: 'Text and link for the main button.' },
  primarybutton: { label: 'Main button', help: 'Text and link for the main button.' },
  privacyhref: { label: 'Privacy link', help: 'Where the privacy takes visitors when clicked.' },
  privacylinklabel: { label: 'Privacy link text', help: 'Text shown on the privacy link.' },
  profileimagealt: { label: 'Profile image description', help: 'Describes the profile image for screen readers and search engines.' },
  profileimagedark: { label: 'Profile photo (dark mode)', help: 'The profile photo shown when the site is in dark mode.' },
  profileimagelight: { label: 'Profile photo (light mode)', help: 'The profile photo shown when the site is in light mode.' },
  proof: { label: 'Proof point', help: 'Short evidence line that backs up the headline (for example a stat or client count).' },
  qualifier: { label: 'Qualifier line', help: 'Short qualifying text shown near the headline.' },
  questionslabel: { label: 'Questions text', help: 'Text shown on the questions.' },
  reassurance: { label: 'Reassurance text', help: 'Short reassuring text shown near the button (for example ‘No commitment’).' },
  relatedservices: { label: 'Related services', help: 'The related services shown in this section. Add, remove, or reorder them.' },
  relatedtitle: { label: 'Related heading', help: 'Heading shown for the related.' },
  resultlabel: { label: 'Result text', help: 'Text shown on the result.' },
  reviewlabel: { label: 'Review text', help: 'Text shown on the review.' },
  reviewslimit: { label: 'Number of reviews', help: 'How many reviews to show.' },
  safetynet: { label: 'Safety net box', help: 'The reassurance box shown in this section (title and supporting text).' },
  secondaryaction: { label: 'Second button', help: 'Text and link for the second button.' },
  secondarybutton: { label: 'Second button', help: 'Text and link for the second button.' },
  sectionclassname: { label: 'Section custom class', help: 'Advanced: custom CSS class names for this section.' },
  sectionid: { label: 'Section ID', help: 'Optional anchor ID so links can jump straight to this section.' },
  selectprompt: { label: 'Choose prompt', help: 'Text shown before a visitor picks an option.' },
  selectpromptbody: { label: 'Choose prompt text', help: 'Supporting text shown before a visitor picks an option.' },
  selectprompttitle: { label: 'Choose prompt heading', help: 'Heading shown before a visitor picks an option.' },
  sendinglabel: { label: 'Sending text', help: 'Text shown on the sending.' },
  show: { label: 'Show', help: 'Turn on or off to show or hide this element.' },
  showgithubstars: { label: 'Show github stars', help: 'Turn on to show the github stars; turn off to hide it.' },
  showgooglereviews: { label: 'Show google reviews', help: 'Turn on to show the google reviews; turn off to hide it.' },
  showverifiedbadge: { label: 'Show verified badge', help: 'Turn on to show the verified badge; turn off to hide it.' },
  socialiconalt: { label: 'Social icon image description', help: 'Describes the social icon image for screen readers and search engines.' },
  socialiconsrc: { label: 'Social icon image', help: 'The image shown for the social icon. Choose from the media library or upload one.' },
  steplabel: { label: 'Step text', help: 'Text shown on the step.' },
  sticky: { label: 'Stick to screen', help: 'Turn on to keep this visible while visitors scroll.' },
  stillunsurelabel: { label: 'Still unsure text', help: 'Text shown on the still unsure.' },
  subheading: { label: 'Subheading', help: 'Supporting line shown under the heading.' },
  subheadline: { label: 'Subheadline', help: 'Supporting line shown under the headline.' },
  submitlabel: { label: 'Submit text', help: 'Text shown on the submit.' },
  subsections: { label: 'Subsections', help: 'The subsections shown in this section. Add, remove, or reorder them.' },
  summarycolumns: { label: 'Summary columns', help: 'The summary columns shown in this section. Add, remove, or reorder them.' },
  summaryheading: { label: 'Summary heading', help: 'Heading shown for the summary.' },
  summaryitems: { label: 'Summary items', help: 'The summary entries shown. Add, remove, or reorder them.' },
  summaryseparator: { label: 'Show summary divider', help: 'Turn on to show a divider line in the summary.' },
  supportinglinkhref: { label: 'Supporting link', help: 'Where the supporting link takes visitors when clicked.' },
  supportinglinklabel: { label: 'Supporting link text', help: 'Text shown on the supporting link.' },
  supportingtext: { label: 'Supporting text', help: 'Text shown on the supporting.' },
  supportingtitle: { label: 'Supporting heading', help: 'Heading shown for the supporting.' },
  table: { label: 'Table', help: 'The table of information shown in this section.' },
  termsconnector: { label: 'Terms sentence connector', help: 'The word joining the terms links (for example ‘and’).' },
  termslinks: { label: 'Terms links', help: 'The terms links shown in this section. Add, remove, or reorder them.' },
  tiers: { label: 'Tiers', help: 'The tiers shown in this section. Add, remove, or reorder them.' },
  timelineheading: { label: 'Timeline heading', help: 'Heading shown for the timeline.' },
  timelineitems: { label: 'Timeline items', help: 'The timeline entries shown. Add, remove, or reorder them.' },
  triggerid: { label: 'Trigger section ID', help: 'Advanced: the section ID that makes this appear once scrolled past.' },
  trustedby: { label: 'Trusted-by logos', help: 'The logos and names shown in the ‘trusted by’ strip.' },
  trustedbylabel: { label: 'Trusted by text', help: 'Text shown on the trusted by.' },
  trustlogos: { label: 'Trust logos', help: 'The trust logos shown in this section. Add, remove, or reorder them.' },
  truststripitems: { label: 'Trust strip items', help: 'The trust strip entries shown. Add, remove, or reorder them.' },
  truststripverifiedlabel: { label: 'Trust strip verified text', help: 'Text shown on the trust strip verified.' },
  vatnote: { label: 'Vat note', help: 'Small print shown with the vat.' },
  verifiedlabel: { label: 'Verified text', help: 'Text shown on the verified.' },
  whatsapplabel: { label: 'Whatsapp text', help: 'Text shown on the whatsapp.' },
};
