// Shared editor field vocabulary for the VD platform.
// Non-technical labels and hover help for Puck editor properties, keyed by
// lowercased prop name. The dictionary supersedes labels declared in block
// files; per-site overrides live in puck/field-vocabulary.site.ts and win
// over these base entries. Keys with no entry fall back to humanizeFieldKey().
//
// Generated from the platform-wide field inventory (2026-08-08); edit freely —
// this file is data, not code.

export type FieldVocabEntry = {
  label: string;
  help?: string;
};

export const BASE_FIELD_VOCABULARY: Record<string, FieldVocabEntry> = {
  accent: { label: 'Highlighted text', help: 'Text that receives emphasis in the heading.' },
  address: { label: 'Address', help: 'The address shown to visitors.' },
  advanced: { label: 'Advanced (developers)', help: 'Technical settings — IDs, custom classes and fixed sizes. Safe to ignore.' },
  advocateslugs: { label: 'Advocate (internal names)', help: 'Advanced: internal names identifying which advocate to show.' },
  align: { label: 'Alignment', help: 'How content aligns within the available width.' },
  allchapterslabel: { label: '‘All chapters’ label', help: 'Text for the filter option that shows every chapter.' },
  alllabel: { label: '‘All’ filter text', help: 'Text for the filter option that shows everything.' },
  alt: { label: 'Image description', help: 'Describes the image for screen readers and search engines.' },
  aspectratio: { label: 'Image shape', help: 'The width-to-height shape images are cropped to, so they don’t stretch.' },
  authorname: { label: 'Author name', help: 'The author’s name as it should appear.' },
  authorrole: { label: 'Author role', help: 'The author’s role, position or title.' },
  awards: { label: 'Awards', help: 'The awards displayed in this section.' },
  background: { label: 'Background colour', help: 'The background colour treatment for this section.' },
  backgroundimagealt: { label: 'Background image description', help: 'Describes the background image for screen readers and search engines.' },
  backgroundimagesrc: { label: 'Background image', help: 'The background image shown. Choose from the media library or upload one.' },
  backhref: { label: 'Back link', help: 'Where the back link takes visitors.' },
  backlabel: { label: 'Back link text', help: 'Text shown on the back link.' },
  badge: { label: 'Badge text', help: 'Small highlight tag shown on this item.' },
  badges: { label: 'Badges', help: 'Small highlight tags shown in this section.' },
  body: { label: 'Body text', help: 'The main paragraph text for this section.' },
  bodymarkdown: { label: 'Body text', help: 'The main text for this section. Supports simple formatting.' },
  brandhref: { label: 'Brand link', help: 'Where clicking the brand name or logo takes visitors — usually the home page.' },
  brandname: { label: 'Brand name', help: 'The site or organisation name shown.' },
  brandtitle: { label: 'Brand name', help: 'The site or organisation name shown in the header.' },
  buttonlabel: { label: 'Button text', help: 'Text shown on the button. Keep it short — two or three words.' },
  buttonlink: { label: 'Button link', help: 'Where the button takes visitors. Pick a page or paste a web address.' },
  caption: { label: 'Caption', help: 'Short text shown under the image.' },
  cards: { label: 'Cards', help: 'The cards shown in this section. Add, remove, or reorder them.' },
  categories: { label: 'Categories', help: 'The categories shown in this section.' },
  category: { label: 'Category', help: 'The category this item belongs to.' },
  chapterlabel: { label: 'Chapter field label', help: 'Label shown above the chapter selector on the form.' },
  chapterplaceholder: { label: 'Chapter field hint', help: 'Hint text shown in the chapter selector.' },
  charityslugs: { label: 'Charity (internal names)', help: 'Advanced: internal names identifying which charity to show.' },
  classname: { label: 'Custom class', help: 'Advanced: custom CSS class names for developers.' },
  clearlabel: { label: '‘Clear’ text', help: 'Text for the control that clears the current filter or selection.' },
  columns: { label: 'Number of columns', help: 'How many columns the items are arranged into on larger screens.' },
  commitmentitems: { label: 'Commitments', help: 'The commitments shown. Add, remove, or reorder them.' },
  commitmentsubtitle: { label: 'Commitments subtitle', help: 'Supporting line shown under the commitments heading.' },
  commitmenttitle: { label: 'Commitments heading', help: 'The heading shown above the commitments.' },
  communicationpreferencesdescription: { label: 'Communication preferences text', help: 'Supporting text shown for the communication preferences.' },
  communicationpreferencestitle: { label: 'Communication preferences heading', help: 'Heading shown for the communication preferences.' },
  contactdescription: { label: 'Contact description', help: 'Supporting text shown with the contact details.' },
  contactheading: { label: 'Contact heading', help: 'Heading shown above the contact details.' },
  contacthint: { label: 'Contact hint', help: 'Short helper text shown near the contact details.' },
  contacttitle: { label: 'Contact heading', help: 'Heading shown above the contact details.' },
  copyright: { label: 'Copyright notice', help: 'The copyright line shown in the footer.' },
  ctabuttons: { label: 'Buttons', help: 'The buttons shown in this section. Add, remove, or reorder them.' },
  ctadescription: { label: 'Call-to-action description', help: 'Supporting text shown with the buttons.' },
  ctaheading: { label: 'Call-to-action heading', help: 'Heading shown above the buttons.' },
  ctahref: { label: 'Button link', help: 'Where the button takes visitors. Pick a page or paste a web address.' },
  ctaintro: { label: 'Button introduction', help: 'Short text shown above the buttons.' },
  ctalabel: { label: 'Button text', help: 'Text shown on the button. Keep it short — two or three words.' },
  ctaprimaryhref: { label: 'Main button link', help: 'Where the main button takes visitors.' },
  ctaprimarylabel: { label: 'Main button text', help: 'Text shown on the main button.' },
  ctas: { label: 'Buttons', help: 'The buttons shown in this section.' },
  ctasecondaryhref: { label: 'Second button link', help: 'Where the second button takes visitors.' },
  ctasecondarylabel: { label: 'Second button text', help: 'Text shown on the second button.' },
  description: { label: 'Summary text', help: 'Supporting paragraph shown below the heading.' },
  descriptionmarkdown: { label: 'Summary text', help: 'Supporting text for this section. Supports simple formatting.' },
  details: { label: 'Details', help: 'Extra detail text shown for this item.' },
  email: { label: 'Email address', help: 'The email address shown or used by this section.' },
  emaillabel: { label: 'Email field label', help: 'Label shown above the email box on the form.' },
  emailplaceholder: { label: 'Email field hint', help: 'Grey hint text inside the email box before anyone types.' },
  emptybody: { label: 'Empty-state text', help: 'Text shown when there is nothing to display yet.' },
  emptystatelabel: { label: 'Empty-state message', help: 'Text shown when there is nothing to display yet.' },
  emptytitle: { label: 'Empty-state heading', help: 'Heading shown when there is nothing to display yet.' },
  entries: { label: 'Entries', help: 'The entries shown in this section. Add, remove, or reorder them.' },
  errormessage: { label: 'Error message', help: 'Text shown if something goes wrong.' },
  eyebrow: { label: 'Section label', help: 'Short label shown above the heading.' },
  faqcarddescription: { label: 'FAQ card text', help: 'Supporting text shown for the FAQ card.' },
  faqcardtitle: { label: 'FAQ card heading', help: 'Heading shown for the FAQ card.' },
  faqs: { label: 'Questions and answers', help: 'The questions and answers shown. Add, remove, or reorder them.' },
  featuredslug: { label: 'Featured item', help: 'Which item to feature in this section.' },
  features: { label: 'Feature list', help: 'The features shown in this section. Add, remove, or reorder them.' },
  fellows: { label: 'Fellows', help: 'The fellows shown in this section.' },
  fieldlabel: { label: 'Field label', help: 'Label shown above this form field.' },
  fileurl: { label: 'File', help: 'The file visitors can download. Choose from the media library or upload one.' },
  firstnamelabel: { label: 'First name field label', help: 'Label shown above the first-name box on the form.' },
  firstnameplaceholder: { label: 'First name field hint', help: 'Grey hint text inside the first-name box.' },
  focusitems: { label: 'Focus items', help: 'The focus entries shown. Add, remove, or reorder them.' },
  footermarkdown: { label: 'Footer text', help: 'Text shown at the bottom of this section. Supports simple formatting.' },
  footertext: { label: 'Footer text', help: 'Text shown at the bottom of this section.' },
  footnote: { label: 'Footnote', help: 'Small print shown at the bottom of this section.' },
  formconsentnote: { label: 'Consent note', help: 'Small print about consent shown near the submit button.' },
  formdescription: { label: 'Form description', help: 'Supporting text shown above the form.' },
  formtitle: { label: 'Form heading', help: 'Heading shown above the form.' },
  gutter: { label: 'Gap between items', help: 'Space between columns or cards.' },
  heading: { label: 'Heading', help: 'The main heading text for this section.' },
  headingaccent: { label: 'Highlighted heading text', help: 'The part of the heading that receives emphasis.' },
  headingend: { label: 'Heading (continued)', help: 'Closing part of the main heading text.' },
  headinglevel: { label: 'Heading importance', help: 'Advanced: sets the heading level (H1–H6) for accessibility and search engines.' },
  headingstart: { label: 'Heading', help: 'Opening part of the main heading text.' },
  headingtag: { label: 'Heading importance', help: 'Advanced: sets the heading level (H1–H6) for accessibility and search engines.' },
  headline: { label: 'Headline', help: 'The large headline text for this section.' },
  height: { label: 'Height (px)', help: 'Advanced: fixed height in pixels.' },
  herodescription: { label: 'Banner description', help: 'Supporting text in the top banner.' },
  heroeyebrow: { label: 'Banner label', help: 'Short label shown above the banner heading.' },
  heroimage: { label: 'Banner image', help: 'The image shown in the top banner.' },
  heromapalt: { label: 'Banner map image description', help: 'Describes the banner map image for screen readers and search engines.' },
  heromapsrc: { label: 'Banner map image', help: 'The image shown for the banner map. Choose from the media library or upload one.' },
  heroprimaryctahref: { label: 'Banner main button link', help: 'Where the banner’s main button takes visitors.' },
  heroprimaryctalabel: { label: 'Banner main button text', help: 'Text on the banner’s main button.' },
  herosecondaryctahref: { label: 'Banner second button link', help: 'Where the banner’s second button takes visitors.' },
  herosecondaryctalabel: { label: 'Banner second button text', help: 'Text on the banner’s second button.' },
  herotitle: { label: 'Banner heading', help: 'The main heading in the top banner.' },
  highlights: { label: 'Highlights', help: 'The key points shown in this section.' },
  historyintro: { label: 'History text', help: 'Supporting text shown for the history.' },
  historylinkhref: { label: 'History link', help: 'Where the history link takes visitors when clicked.' },
  historylinklabel: { label: 'History link text', help: 'Text shown on the history link.' },
  homelabel: { label: 'Home link text', help: 'Text for the link back to the home page.' },
  id: { label: 'Section ID', help: 'Optional anchor ID so links can jump straight to this section.' },
  image: { label: 'Image', help: 'The picture shown. Choose from the media library or upload one.' },
  imagealt: { label: 'Image description', help: 'Describes the image for screen readers and search engines.' },
  imageheading: { label: 'Image heading', help: 'Heading shown for the image.' },
  imageheight: { label: 'Image height (px)', help: 'Advanced: fixed image height in pixels.' },
  imageposition: { label: 'Image position', help: 'Which side of the text the image sits on.' },
  imageratio: { label: 'Image shape', help: 'The width-to-height shape the image is cropped to.' },
  imagesrc: { label: 'Image', help: 'The picture shown. Choose from the media library or upload one.' },
  imageurl: { label: 'Image', help: 'The picture shown. Choose from the media library or upload one.' },
  imagewidth: { label: 'Image width (px)', help: 'Advanced: fixed image width in pixels.' },
  inclusions: { label: 'What’s included', help: 'The list of things included.' },
  institutionlabel: { label: 'Institution field label', help: 'Label shown above the institution box on the form.' },
  institutionplaceholder: { label: 'Institution field hint', help: 'Grey hint text inside the institution box.' },
  intro: { label: 'Introduction', help: 'Opening text shown at the start of this section.' },
  intromarkdown: { label: 'Introduction', help: 'Opening text for this section. Supports simple formatting.' },
  introtext: { label: 'Introduction', help: 'Opening text shown at the start of this section.' },
  involvementdescription: { label: 'Involvement text', help: 'Supporting text shown for the involvement.' },
  involvementeyebrow: { label: 'Involvement label', help: 'Short label shown above the involvement heading.' },
  involvementheading: { label: 'Involvement heading', help: 'Heading shown for the involvement.' },
  involvementoptions: { label: 'Ways to get involved', help: 'The get-involved options shown. Add, remove, or reorder them.' },
  isstartingfrom: { label: 'Show ‘from’ before price', help: 'Turn on to show the price as a starting (‘from’) price.' },
  items: { label: 'List items', help: 'The entries shown in this section. Add, remove, or reorder them.' },
  label: { label: 'Label', help: 'Short text shown for this item.' },
  lastnamelabel: { label: 'Last name field label', help: 'Label shown above the last-name box on the form.' },
  lastnameplaceholder: { label: 'Last name field hint', help: 'Grey hint text inside the last-name box.' },
  lastupdated: { label: 'Last updated', help: 'The date shown to visitors as the most recent update.' },
  layout: { label: 'Layout', help: 'Spacing, width and alignment settings for this section.' },
  lead: { label: 'Lead paragraph', help: 'The opening paragraph, shown larger than normal text.' },
  leaders: { label: 'Leaders', help: 'The leaders shown in this section.' },
  legal: { label: 'Legal links', help: 'Links to legal pages such as privacy and terms.' },
  limit: { label: 'Maximum items shown', help: 'The most items this section will display.' },
  links: { label: 'Links', help: 'The list of links shown. Add, remove, or reorder them.' },
  listitems: { label: 'List items', help: 'The entries shown in this list.' },
  location: { label: 'Location', help: 'The place shown for this item.' },
  logoalt: { label: 'Logo description', help: 'Describes the logo for screen readers and search engines.' },
  logoframeheightpx: { label: 'Logo frame height (px)', help: 'Advanced: height of the box the logo sits in, in pixels.' },
  logoframewidthpx: { label: 'Logo frame width (px)', help: 'Advanced: width of the box the logo sits in, in pixels.' },
  logoimageoffsetx: { label: 'Move logo left/right (px)', help: 'Fine-tune: moves the logo left (minus numbers) or right (plus numbers) within its frame.' },
  logoimageoffsety: { label: 'Move logo up/down (px)', help: 'Fine-tune: moves the logo up (minus numbers) or down (plus numbers) within its frame.' },
  logooffsetx: { label: 'Move logo left/right (px)', help: 'Fine-tune: moves the logo left (minus numbers) or right (plus numbers).' },
  logooffsety: { label: 'Move logo up/down (px)', help: 'Fine-tune: moves the logo up (minus numbers) or down (plus numbers).' },
  logos: { label: 'Logos', help: 'The logos displayed in this section.' },
  logosrc: { label: 'Logo image', help: 'The logo shown. Choose from the media library or upload one.' },
  logourl: { label: 'Logo image', help: 'The logo shown. Choose from the media library or upload one.' },
  logowidthpx: { label: 'Logo width (px)', help: 'How wide the logo appears, in pixels.' },
  marginbottom: { label: 'Space below section', help: 'Gap between this section and the one below it.' },
  marginleft: { label: 'Space left of section', help: 'Gap to the left of this section.' },
  marginright: { label: 'Space right of section', help: 'Gap to the right of this section.' },
  margintop: { label: 'Space above section', help: 'Gap between this section and the one above it.' },
  maxitems: { label: 'Maximum items shown', help: 'The most items this section will display.' },
  maxwidth: { label: 'Content width', help: 'How wide the content can grow on large screens.' },
  members: { label: 'Members', help: 'The members shown in this section.' },
  membershipbadge: { label: 'Membership form badge', help: 'Short highlight text shown above the membership form heading.' },
  membershipimagealt: { label: 'Membership image description', help: 'Describes the membership image for screen readers and search engines.' },
  membershipimagesrc: { label: 'Membership image', help: 'The membership image shown. Choose from the media library or upload one.' },
  menulabel: { label: 'Menu label', help: 'Text shown on the menu button.' },
  menulinks: { label: 'Menu links', help: 'The links shown in the menu.' },
  message: { label: 'Message', help: 'The message text.' },
  messagelabel: { label: 'Message field label', help: 'Label shown above the message box on the form.' },
  messageplaceholder: { label: 'Message field hint', help: 'Grey hint text inside the message box.' },
  mission: { label: 'Mission text', help: 'The mission statement shown in this section.' },
  missioneyebrow: { label: 'Mission label', help: 'Short label shown above the mission heading.' },
  missionheading: { label: 'Mission heading', help: 'Heading shown for the mission.' },
  missionlabel: { label: 'Mission label', help: 'Short label shown above the mission statement.' },
  missionmapalt: { label: 'Mission map image description', help: 'Describes the mission map image for screen readers and search engines.' },
  missionmapcaption: { label: 'Mission map caption', help: 'Short text shown under the mission map.' },
  missionmapsrc: { label: 'Mission map image', help: 'The image shown for the mission map. Choose from the media library or upload one.' },
  missionparagraphs: { label: 'Mission paragraphs', help: 'The paragraphs of the mission statement. Add, remove, or reorder them.' },
  mode: { label: 'Display style', help: 'Changes how this section is presented.' },
  morearticleshint: { label: '‘More articles’ hint', help: 'Short helper text shown near the ‘more articles’ link.' },
  morearticleshref: { label: '‘More articles’ link', help: 'Where the ‘more articles’ link takes visitors.' },
  morearticleslabel: { label: '‘More articles’ text', help: 'Text for the link to more articles.' },
  moreinfoheading: { label: '‘More info’ heading', help: 'Heading for the additional information area.' },
  motivationintro: { label: 'Motivation text', help: 'Supporting text shown for the motivation.' },
  motivationlinkhref: { label: 'Motivation link', help: 'Where the motivation link takes visitors when clicked.' },
  motivationlinklabel: { label: 'Motivation link text', help: 'Text shown on the motivation link.' },
  name: { label: 'Name', help: 'The name as it should appear.' },
  navgroups: { label: 'Menu groups', help: 'Groups of links in the navigation menu.' },
  navlinks: { label: 'Menu links', help: 'The links shown in the navigation menu.' },
  newsletterbenefits: { label: 'Newsletter benefits', help: 'The list of benefits shown next to the newsletter sign-up.' },
  newslettercarddescription: { label: 'Newsletter card text', help: 'Supporting text shown for the newsletter card.' },
  newslettercardtitle: { label: 'Newsletter card heading', help: 'Heading shown for the newsletter card.' },
  newsletterdescription: { label: 'Newsletter text', help: 'Supporting text shown for the newsletter.' },
  newslettereyebrow: { label: 'Newsletter label', help: 'Short label shown above the newsletter heading.' },
  newsletterhint: { label: 'Newsletter hint', help: 'Short helper text shown near the newsletter sign-up.' },
  newsletterprivacynote: { label: 'Newsletter privacy note', help: 'Small print about privacy shown under the newsletter sign-up.' },
  newslettertitle: { label: 'Newsletter heading', help: 'Heading shown above the newsletter sign-up.' },
  nextbuttonlabel: { label: 'Next button text', help: 'Text shown on the ‘next’ button.' },
  optoutawardslabel: { label: 'Opt out awards text', help: 'Text shown on the opt out awards.' },
  optoutconferenceslabel: { label: 'Opt out conferences text', help: 'Text shown on the opt out conferences.' },
  optoutnewsletterlabel: { label: 'Opt out newsletter text', help: 'Text shown on the opt out newsletter.' },
  paddingbottom: { label: 'Space below (inside)', help: 'Space between this section’s bottom edge and its content.' },
  paddingleft: { label: 'Space left (inside)', help: 'Space between this section’s left edge and its content.' },
  paddingright: { label: 'Space right (inside)', help: 'Space between this section’s right edge and its content.' },
  paddingtop: { label: 'Space above (inside)', help: 'Space between this section’s top edge and its content.' },
  pagelabel: { label: 'Page label', help: 'Short label identifying this page.' },
  panelimagealt: { label: 'Panel image description', help: 'Describes the panel image for screen readers and search engines.' },
  panelimagesrc: { label: 'Panel image', help: 'The panel image shown. Choose from the media library or upload one.' },
  paragraphs: { label: 'Paragraphs', help: 'The paragraphs of text shown in this section.' },
  people: { label: 'People', help: 'The people shown in this section. Add, remove, or reorder them.' },
  personimagesrc: { label: 'Photo', help: 'The person’s photo. Choose from the media library or upload one.' },
  personname: { label: 'Name', help: 'The person’s name as it should appear.' },
  persontitle: { label: 'Role or title', help: 'The person’s role, position or title.' },
  photobreakalt: { label: 'Photo break image description', help: 'Describes the photo break image for screen readers and search engines.' },
  photobreaksrc: { label: 'Photo break image', help: 'The image shown for the photo break. Choose from the media library or upload one.' },
  placeholder: { label: 'Hint text', help: 'Grey hint text shown inside the box before anyone types.' },
  playlabel: { label: '‘Play’ text', help: 'Text for the play control.' },
  posts: { label: 'Posts', help: 'The articles or posts shown in this section.' },
  previousbuttonlabel: { label: 'Previous button text', help: 'Text shown on the ‘previous’ button.' },
  price: { label: 'Price', help: 'The price shown for this item.' },
  pricelabel: { label: 'Price label', help: 'Text shown next to the price.' },
  primarycta: { label: 'Main button', help: 'Text and link for the main button.' },
  primaryctahref: { label: 'Main button link', help: 'Where the main button takes visitors.' },
  primaryctalabel: { label: 'Main button text', help: 'Text shown on the main button.' },
  primaryctatext: { label: 'Main button text', help: 'Text shown on the main button.' },
  primaryctaurl: { label: 'Main button link', help: 'Where the main button takes visitors.' },
  primarylabel: { label: 'Main button text', help: 'Text shown on the main button.' },
  primarylink: { label: 'Main button link', help: 'Where the main button takes visitors.' },
  privacylabel: { label: 'Privacy link text', help: 'Text for the privacy policy link.' },
  privacynoticebody: { label: 'Privacy notice text', help: 'Supporting text shown for the privacy notice.' },
  privacynoticetitle: { label: 'Privacy notice heading', help: 'Heading shown for the privacy notice.' },
  programmark: { label: 'Program name', help: 'Short program name shown in the banner (for example ‘Fellowship Program’).' },
  promptlabel: { label: 'Prompt text', help: 'Short text inviting visitors to act.' },
  quote: { label: 'Quote', help: 'The quotation text displayed in this section.' },
  rating: { label: 'Rating', help: 'The star rating shown (for example 4.8).' },
  regions: { label: 'Regions', help: 'The regions listed in this section.' },
  regionsdescription: { label: 'Regions text', help: 'Supporting text shown for the regions.' },
  regionseyebrow: { label: 'Regions label', help: 'Short label shown above the regions heading.' },
  regionsheading: { label: 'Regions heading', help: 'Heading shown for the regions.' },
  resources: { label: 'Resources', help: 'The resources listed in this section.' },
  resourcesintro: { label: 'Resources introduction', help: 'Opening text shown above the resources list.' },
  reviewcount: { label: 'Number of reviews', help: 'How many reviews the rating is based on.' },
  reviewids: { label: 'Selected reviews', help: 'Advanced: internal names of the specific reviews to show. Leave empty to show all reviews.' },
  role: { label: 'Role', help: 'The person’s role, position or title.' },
  searchplaceholder: { label: 'Search box hint', help: 'Grey hint text shown inside the search box before anyone types.' },
  secondarycta: { label: 'Second button', help: 'Text and link for the second button.' },
  secondaryctahref: { label: 'Second button link', help: 'Where the second button takes visitors.' },
  secondaryctalabel: { label: 'Second button text', help: 'Text shown on the second button.' },
  secondaryctatext: { label: 'Second button text', help: 'Text shown on the second button.' },
  secondaryctaurl: { label: 'Second button link', help: 'Where the second button takes visitors.' },
  secondarylabel: { label: 'Second button text', help: 'Text shown on the second button.' },
  secondarylink: { label: 'Second button link', help: 'Where the second button takes visitors.' },
  sections: { label: 'Sections', help: 'The groups of content inside this block. Add, remove, or reorder them.' },
  seektext: { label: 'Seek text', help: 'Text shown on the seek.' },
  services: { label: 'Services', help: 'The services listed in this section.' },
  showcategory: { label: 'Show category', help: 'Turn on to show each item’s category.' },
  showchapterfilters: { label: 'Show chapter filters', help: 'Turn on to let visitors filter by chapter.' },
  showfeatured: { label: 'Show featured item', help: 'Turn on to highlight a featured item.' },
  showhovercard: { label: 'Show hover details', help: 'Turn on to show extra details when visitors hover over an item.' },
  showondesktop: { label: 'Show on desktop', help: 'Turn on to show this section on desktop screens.' },
  showonmobile: { label: 'Show on mobile', help: 'Turn on to show this section on phones.' },
  showprice: { label: 'Show prices', help: 'Turn on to show prices.' },
  showsearch: { label: 'Show search box', help: 'Turn on to show the search box.' },
  social: { label: 'Social links', help: 'Links to social media profiles.' },
  socials: { label: 'Social links', help: 'Links to social media profiles.' },
  source: { label: 'Source', help: 'Where this quote or information comes from.' },
  src: { label: 'Image', help: 'The picture shown. Choose from the media library or upload one.' },
  startdescription: { label: 'Start text', help: 'Supporting text shown for the start.' },
  startemailaddress: { label: '‘Start a chapter’ email', help: 'The email address shown for people who want to start a new chapter.' },
  startemailbody: { label: 'Start email text', help: 'Supporting text shown for the start email.' },
  startemailtitle: { label: 'Start email heading', help: 'Heading shown for the start email.' },
  starteyebrow: { label: 'Start label', help: 'Short label shown above the start heading.' },
  startheading: { label: 'Start heading', help: 'Heading shown for the start.' },
  startimagealt: { label: 'Start image description', help: 'Describes the start image for screen readers and search engines.' },
  startimagesrc: { label: 'Start image', help: 'The start image shown. Choose from the media library or upload one.' },
  startprimaryctahref: { label: 'Start primary button link', help: 'Where the start primary button takes visitors when clicked.' },
  startprimaryctalabel: { label: 'Start primary button text', help: 'Text shown on the start primary button.' },
  startsecondaryctahref: { label: 'Start secondary button link', help: 'Where the start secondary button takes visitors when clicked.' },
  startsecondaryctalabel: { label: 'Start secondary button text', help: 'Text shown on the start secondary button.' },
  stats: { label: 'Statistics', help: 'The numbers and captions displayed in this section.' },
  stayslug: { label: 'Stay (internal name)', help: 'Advanced: the internal name that identifies the stay.' },
  steps: { label: 'Steps', help: 'The steps shown in this section, in order.' },
  story: { label: 'Story', help: 'The story text shown in this section.' },
  submitbuttonlabel: { label: 'Submit button text', help: 'Text shown on the form’s submit button.' },
  subtitle: { label: 'Subtitle', help: 'Supporting line shown under the title.' },
  successmessage: { label: 'Success message', help: 'Text shown after the form is submitted successfully.' },
  summary: { label: 'Summary', help: 'A short summary shown for this item.' },
  tagline: { label: 'Tagline', help: 'Short memorable phrase shown with the brand or heading.' },
  termslabel: { label: 'Terms link text', help: 'Text for the terms and conditions link.' },
  testimonials: { label: 'Testimonials', help: 'The testimonials shown in this section.' },
  title: { label: 'Title', help: 'The main title for this section.' },
  titleprimary: { label: 'Title (first part)', help: 'Opening part of the title.' },
  titlesecondary: { label: 'Title (second part)', help: 'Closing part of the title.' },
  tone: { label: 'Colour tone', help: 'Choose the colour treatment for this section.' },
  type: { label: 'Type', help: 'The kind of item this is.' },
  url: { label: 'Link', help: 'The web address this points to.' },
  usepolicies: { label: 'Show policy links', help: 'Turn on to show links to policies.' },
  useshortsoverlay: { label: 'Shorts-style overlay', help: 'Turn on to show video details overlaid on the video, like YouTube Shorts.' },
  values: { label: 'Values', help: 'The values listed in this section.' },
  variant: { label: 'Style variant', help: 'Choose an alternative look for this section.' },
  videoslugs: { label: 'Video (internal names)', help: 'Advanced: internal names identifying which video to show.' },
  videosrc: { label: 'Video', help: 'The video shown. Choose from the media library or paste a video link.' },
  viewallhref: { label: '‘View all’ link', help: 'Where the ‘view all’ link takes visitors.' },
  viewalllabel: { label: '‘View all’ text', help: 'Text for the link that shows everything.' },
  visitlabel: { label: '‘Visit’ text', help: 'Text for the visit link or button.' },
  watchlabel: { label: '‘Watch’ text', help: 'Text for the watch link or button.' },
  ways: { label: 'Ways to contribute', help: 'The list of ways to contribute or get involved. Add, remove, or reorder them.' },
  whatsappmessage: { label: 'WhatsApp message', help: 'The pre-filled message when visitors contact you on WhatsApp.' },
  wrapperclassname: { label: 'Wrapper custom class', help: 'Advanced: custom CSS class names for the section wrapper.' },
};

import { SITE_FIELD_VOCABULARY } from '@/puck/field-vocabulary.site';

const TOKEN_MAP: Record<string, string> = {
  cta: 'button',
  href: 'link',
  url: 'link',
  src: 'image',
  img: 'image',
  nav: 'menu',
  faq: 'FAQ',
  faqs: 'FAQs',
  px: '(px)',
  id: 'ID',
  hero: 'banner',
  markdown: 'text'
};

/** Look up a vocabulary entry: site override first, then base. */
export function lookupFieldVocab(propName: string): FieldVocabEntry | undefined {
  const key = propName.toLowerCase();
  return SITE_FIELD_VOCABULARY[key] ?? BASE_FIELD_VOCABULARY[key];
}

/** Fallback: turn a camelCase prop name into a readable sentence-case label. */
export function humanizeFieldKey(propName: string): string {
  const words = propName
    .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
    .replace(/([A-Z]+)([A-Z][a-z])/g, '$1 $2')
    .split(/[\s_-]+/)
    .filter(Boolean)
    .map((word) => {
      const lower = word.toLowerCase();
      return TOKEN_MAP[lower] ?? lower;
    });
  const sentence = words.join(' ');
  return sentence ? sentence.charAt(0).toUpperCase() + sentence.slice(1) : propName;
}
