import { describe, expect, it } from 'bun:test'

import { NewsArticle } from '@/models/NewsArticle'
import {
  postProcessSEO,
  persistAutoGeneratedSEO,
  shouldGenerateSEOForArticle,
} from './seo.server'

type NewsArticleModel = typeof NewsArticle & { findOneAndUpdate: unknown }

function stubFindOneAndUpdate() {
  const model = NewsArticle as unknown as NewsArticleModel
  const original = model.findOneAndUpdate
  const captured = {
    query: null as Record<string, unknown> | null,
    update: null as Record<string, unknown> | null,
    options: null as Record<string, unknown> | null,
  }

  ;(model as unknown as {
    findOneAndUpdate: (
      query: Record<string, unknown>,
      update: Record<string, unknown>,
      options: Record<string, unknown>
    ) => { exec: () => Promise<{ _id: string } | null> }
  }).findOneAndUpdate = (query, update, options) => {
    captured.query = query
    captured.update = update
    captured.options = options
    return {
      exec: async () => ({ _id: 'stub-id' }),
    }
  }

  return {
    captured,
    restore: () => {
      model.findOneAndUpdate = original
    },
  }
}

describe('shouldGenerateSEOForArticle', () => {
  it('blocks manual SEO from being regenerated without explicit overwrite', () => {
    expect(
      shouldGenerateSEOForArticle(
        {
          title: 'Sample title',
          seoSource: 'manual',
          seoTitle: 'Existing SEO title',
          seoDescription: 'Existing SEO description',
        },
        { force: false },
      ),
    ).toBe(false)
  })

  it('allows manual SEO overwrite only when force is explicitly set', () => {
    expect(
      shouldGenerateSEOForArticle(
        {
          title: 'Sample title',
          seoSource: 'manual',
          seoTitle: 'Existing SEO title',
          seoDescription: 'Existing SEO description',
        },
        { force: true, allowManualOverwrite: true },
      ),
    ).toBe(true)
  })
})

describe('postProcessSEO', () => {
  it('caps seo title and description to practical snippet sizes', () => {
    const rawTitle = 'A'.repeat(140)
    const rawDescription = 'B '.repeat(500).trim()
    const processed = postProcessSEO({
      title: rawTitle,
      description: rawDescription,
      articleTitle: 'Example title',
      articleBody: 'Example article body',
    })

    expect(processed.seoTitle.length).toBeLessThanOrEqual(70)
    expect(processed.seoDescription.length).toBeLessThanOrEqual(170)
  })
})

describe('persistAutoGeneratedSEO', () => {
  it('never overwrites manually set SEO metadata unless explicitly allowed', async () => {
    const stub = stubFindOneAndUpdate()
    try {
      await persistAutoGeneratedSEO(
        'sample-post',
        {
          title: 'New SEO Title',
          description: 'New SEO description',
          generatedAt: new Date(),
          model: 'gpt-4o-mini',
        },
        { allowManualOverwrite: false },
      )

      expect(stub.captured.query).toMatchObject({
        slug: 'sample-post',
      })
      expect(stub.captured.query).toHaveProperty('$or')
      const orFilter = stub.captured.query?.$or
      expect(Array.isArray(orFilter)).toBe(true)
      expect(orFilter).toEqual([
        { seoSource: { $ne: 'manual' } },
        { seoSource: null },
        { seoSource: { $exists: false } },
      ])
    } finally {
      stub.restore()
    }
  })

  it('allows overwriting manual SEO when explicitly permitted', async () => {
    const stub = stubFindOneAndUpdate()
    try {
      await persistAutoGeneratedSEO(
        'sample-post',
        {
          title: 'New SEO Title',
          description: 'New SEO description',
          generatedAt: new Date(),
          model: 'gpt-4o-mini',
        },
        { allowManualOverwrite: true },
      )

      expect(stub.captured.query).toEqual({ slug: 'sample-post' })
    } finally {
      stub.restore()
    }
  })
})
