server {
    server_name designer.velvetdinosaur.com;

    location = /edit {
        return 308 https://velvetdinosaur.com/edit$is_args$args;
    }

    location ^~ /edit/ {
        return 308 https://velvetdinosaur.com$request_uri;
    }

    location = /admin {
        return 308 https://velvetdinosaur.com/admin$is_args$args;
    }

    location ^~ /admin/ {
        return 308 https://velvetdinosaur.com$request_uri;
    }

    location / {
        return 308 https://velvetdinosaur.com/edit;
    }

    listen 443 ssl http2; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/designer.velvetdinosaur.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/designer.velvetdinosaur.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

server {
    if ($host = designer.velvetdinosaur.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    listen 80;
    server_name designer.velvetdinosaur.com;
    return 404; # managed by Certbot
}
