server {
    server_name manage.velvetdinosaur.com;

    include /etc/nginx/snippets/security-headers.conf;

    location = /alertmanager {
        return 308 https://velvetdinosaur.com/admin/alertmanager/;
    }

    location ^~ /alertmanager/ {
        rewrite ^/alertmanager/(.*)$ https://velvetdinosaur.com/admin/alertmanager/$1 permanent;
    }

    location / {
        return 308 https://velvetdinosaur.com/admin/observability;
    }

    listen [::]:443 ssl http2; # managed by Certbot
    listen 443 ssl http2; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/manage.velvetdinosaur.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/manage.velvetdinosaur.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

server {
    if ($host = manage.velvetdinosaur.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    listen 80;
    listen [::]:80;
    server_name manage.velvetdinosaur.com;
    return 404; # managed by Certbot
}
