import { unstable_noStore } from 'next/cache';
import { NextResponse } from 'next/server';
import { getAuth } from '@/lib/auth';
import { connectDB } from '@/lib/db';
import { Asset } from '@/models/Asset';
import {
  computeAltForAsset,
  isImageAssetMime,
  postProcessAltText,
  persistAutoGeneratedAlt,
  shouldGenerateAltForAsset
} from '@/lib/assets/alt-text.server';
import { getAltTextProviderInfo, ProviderNotConfiguredError } from '@/lib/ai/alt-text-provider.server';

const NO_STORE_HEADERS = {
  'Cache-Control': 'no-store',
  Pragma: 'no-cache',
  Expires: '0'
};

type Params = {
  params: Promise<{ id: string }>;
};

function normalizeAssetKey(value: string) {
  let decoded = value;
  try {
    decoded = decodeURIComponent(value);
  } catch {
    decoded = value;
  }
  return decoded.trim().replace(/\\/g, '/').replace(/\/{2,}/g, '/').replace(/\/$/, '');
}

export async function GET(request: Request, { params }: Params) {
  unstable_noStore();
  const auth = getAuth();
  const session = await auth.api.getSession({ headers: request.headers });
  if (!session) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401, headers: NO_STORE_HEADERS });
  }
  const { id } = await params;
  const key = normalizeAssetKey(id);
  if (!key || !key.startsWith('uploads/')) {
    return NextResponse.json({ error: 'Invalid asset key' }, { status: 400, headers: NO_STORE_HEADERS });
  }

  const provider = getAltTextProviderInfo();
  return NextResponse.json(provider, { headers: NO_STORE_HEADERS });
}

export async function POST(request: Request, { params }: Params) {
  unstable_noStore();
  const auth = getAuth();
  const session = await auth.api.getSession({ headers: request.headers });
  if (!session) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401, headers: NO_STORE_HEADERS });
  }

  const { id } = await params;
  const key = normalizeAssetKey(id);
  if (!key || !key.startsWith('uploads/')) {
    return NextResponse.json({ error: 'Invalid asset key' }, { status: 400, headers: NO_STORE_HEADERS });
  }

  const body = (await request.json().catch(() => null)) as { apply?: unknown; alt?: unknown } | null;
  const apply = body?.apply === true;
  const previewAlt = typeof body?.alt === 'string' ? body.alt.trim() : '';

  const conn = await connectDB();
  if (!conn) {
    return NextResponse.json({ error: 'Database unavailable' }, { status: 500, headers: NO_STORE_HEADERS });
  }

  const asset = (await Asset.findOne({ key })
    .select({ key: 1, alt: 1, altSource: 1, mime: 1, width: 1, height: 1 })
    .lean()
    .exec()) as
    | {
        key: string;
        alt?: string | null;
        altSource?: 'manual' | 'auto' | null;
        mime?: string | null;
        width?: number | null;
        height?: number | null;
      }
    | null;

  if (!asset) {
    return NextResponse.json({ error: 'Asset not found' }, { status: 404, headers: NO_STORE_HEADERS });
  }

  if (!isImageAssetMime(asset.mime)) {
    return NextResponse.json({ error: 'Asset is not an image' }, { status: 400, headers: NO_STORE_HEADERS });
  }

  const candidate = {
    key,
    alt: asset.alt ?? undefined,
    altSource: asset.altSource ?? null,
    mime: asset.mime,
    width: asset.width ?? undefined,
    height: asset.height ?? undefined
  };

  if (!shouldGenerateAltForAsset(candidate, { force: apply })) {
    return NextResponse.json(
      { error: 'Alt text is manually set. Clear it first or enable overwrite explicitly.' },
      { status: 409, headers: NO_STORE_HEADERS }
    );
  }

  try {
    if (!apply) {
      const generated = await computeAltForAsset(candidate, request.url, { timeoutMs: 5000 });
      if (!generated) {
        return NextResponse.json(
          { error: 'No alt text generated' },
          { status: 400, headers: NO_STORE_HEADERS }
        );
      }
      return NextResponse.json(
        {
          alt: generated.alt,
          model: generated.model,
          generatedAt: generated.generatedAt.toISOString()
        },
        { headers: NO_STORE_HEADERS }
      );
    }

    const generated = previewAlt
      ? {
          alt: postProcessAltText(previewAlt),
          model: undefined,
          generatedAt: new Date()
        }
      : await computeAltForAsset(candidate, request.url, { timeoutMs: 5000 });
    if (!generated) {
      return NextResponse.json(
        { error: 'No alt text generated' },
        { status: 400, headers: NO_STORE_HEADERS }
      );
    }

    await persistAutoGeneratedAlt(key, generated, { needsReview: true });
    return NextResponse.json(
      {
        ok: true,
        alt: generated.alt,
        altSource: 'auto',
        altGeneratedAt: generated.generatedAt.toISOString(),
        altModel: generated.model || null,
        altNeedsReview: true
      },
      { headers: NO_STORE_HEADERS }
    );
  } catch (error) {
    if (error instanceof ProviderNotConfiguredError) {
      return NextResponse.json(
        { error: `Provider not configured: ${error.providerEnvVar}` },
        { status: 503, headers: NO_STORE_HEADERS }
      );
    }
    const message = error instanceof Error ? error.message : 'Failed to generate alt text';
    return NextResponse.json({ error: message }, { status: 500, headers: NO_STORE_HEADERS });
  }
}
