import { unstable_noStore } from 'next/cache'
import { NextResponse } from 'next/server'

import { requireWorkArticleWriteAccess } from '@/lib/work-article-access'
import { connectDB } from '@/lib/db'
import { isAdminOnly } from '@/lib/site-config'
import { WorkArticle } from '@/models/WorkArticle'
import { computeSEOForArticle, postProcessSEO, persistAutoGeneratedSEO, shouldGenerateSEOForArticle } from '@/lib/work/seo.server'
import {
  getSeoProviderInfo,
  ProviderNotConfiguredError,
} from '@/lib/ai/seo-provider.server'

const NO_STORE_HEADERS = {
  'Cache-Control': 'no-store',
  Pragma: 'no-cache',
  Expires: '0',
}

const DEFAULT_TIMEOUT_MS = 5000

type Params = {
  params: Promise<{ slug: string }>
}

type RequestPayload = {
  apply?: unknown
  force?: unknown
  seoTitle?: unknown
  seoDescription?: unknown
}

function parseBoolean(value: unknown) {
  if (typeof value === 'boolean') return value
  if (typeof value === 'string') {
    const normalized = value.trim().toLowerCase()
    return normalized === 'true' || normalized === '1' || normalized === 'yes' || normalized === 'on'
  }
  return false
}

function normalizeSlug(slug: string) {
  try {
    return decodeURIComponent(slug).trim().toLowerCase()
  } catch {
    return slug.trim().toLowerCase()
  }
}

function manualSeoConflictError(seoSource?: 'manual' | 'auto' | null) {
  return seoSource === 'manual'
    ? 'SEO is manually set. Set force=true to replace it.'
    : 'SEO metadata already exists. Set force=true to replace it.'
}

export async function GET(
  request: Request,
) {
  unstable_noStore()

  if (isAdminOnly()) {
    return NextResponse.json({ error: 'Not found' }, { status: 404, headers: NO_STORE_HEADERS })
  }

  const access = await requireWorkArticleWriteAccess(request)
  if (!access.ok) {
    return access.response
  }

  const provider = getSeoProviderInfo()
  return NextResponse.json(provider, { headers: NO_STORE_HEADERS })
}

export async function POST(
  request: Request,
  { params }: Params,
) {
  unstable_noStore()

  if (isAdminOnly()) {
    return NextResponse.json({ error: 'Not found' }, { status: 404, headers: NO_STORE_HEADERS })
  }

  const access = await requireWorkArticleWriteAccess(request)
  if (!access.ok) {
    return access.response
  }

  const resolved = await params
  const slug = normalizeSlug(resolved.slug || '')
  if (!slug) {
    return NextResponse.json({ error: 'Invalid slug' }, { status: 400, headers: NO_STORE_HEADERS })
  }

  const body = (await request.json().catch(() => null)) as RequestPayload | null
  const apply = body?.apply === true
  const force = parseBoolean(body?.force)
  const previewTitle = typeof body?.seoTitle === 'string' ? body.seoTitle.trim() : ''
  const previewDescription = typeof body?.seoDescription === 'string' ? body.seoDescription.trim() : ''
  const hasPreviewOverride = previewTitle.length > 0 && previewDescription.length > 0

  const conn = await connectDB()
  if (!conn) {
    return NextResponse.json({ error: 'Database unavailable' }, { status: 500, headers: NO_STORE_HEADERS })
  }

  const article = await WorkArticle.findOne({ slug })
    .select({
      title: 1,
      desc: 1,
      content: 1,
      seoTitle: 1,
      seoDescription: 1,
      seoSource: 1,
    })
    .lean()
    .exec()

  if (!article || Array.isArray(article)) {
    return NextResponse.json({ error: 'Article not found' }, { status: 404, headers: NO_STORE_HEADERS })
  }

  const candidate = {
    title: article.title,
    desc: typeof article.desc === 'string' ? article.desc : '',
    content: article.content,
    seoTitle: article.seoTitle ?? null,
    seoDescription: article.seoDescription ?? null,
    seoSource: article.seoSource ?? null,
  }

  if (!candidate.title) {
    return NextResponse.json({ error: 'Article title missing' }, { status: 400, headers: NO_STORE_HEADERS })
  }

  if (!shouldGenerateSEOForArticle(candidate, { force, allowManualOverwrite: force })) {
    return NextResponse.json(
      { error: manualSeoConflictError(candidate.seoSource) },
      { status: 409, headers: NO_STORE_HEADERS }
    )
  }

  try {
    if (!apply) {
      const generated = await computeSEOForArticle(candidate, { timeoutMs: DEFAULT_TIMEOUT_MS })
      if (!generated) {
        return NextResponse.json(
          { error: 'No SEO metadata generated' },
          { status: 400, headers: NO_STORE_HEADERS }
        )
      }

      return NextResponse.json(
        {
          ok: true,
          apply: false,
          seoTitle: generated.seoTitle,
          seoDescription: generated.seoDescription,
          seoModel: generated.model || null,
          seoGeneratedAt: generated.generatedAt.toISOString(),
          seoSource: 'auto',
          seoNeedsReview: true,
        },
        { headers: NO_STORE_HEADERS },
      )
    }

    const articleBody = typeof article.desc === 'string' ? article.desc.trim() : ''
    const processedPreview = hasPreviewOverride
      ? postProcessSEO({
          title: previewTitle,
          description: previewDescription,
          articleTitle: candidate.title,
          articleBody,
        })
      : null

    const generated = processedPreview
      ? {
          seoTitle: processedPreview.seoTitle,
          seoDescription: processedPreview.seoDescription,
          model: undefined,
          generatedAt: new Date(),
        }
      : await (async () => {
          const auto = await computeSEOForArticle(candidate, { timeoutMs: DEFAULT_TIMEOUT_MS })
          if (!auto) return null
          return {
            seoTitle: auto.seoTitle,
            seoDescription: auto.seoDescription,
            model: auto.model,
            generatedAt: auto.generatedAt,
          }
        })()

    if (!generated) {
      return NextResponse.json(
        { error: 'No SEO metadata generated' },
        { status: 400, headers: NO_STORE_HEADERS }
      )
    }

    const persisted = await persistAutoGeneratedSEO(
      slug,
      {
        title: generated.seoTitle,
        description: generated.seoDescription,
        model: generated.model,
        generatedAt: generated.generatedAt,
      },
      {
        needsReview: true,
        allowManualOverwrite: force,
      },
    )

    if (!persisted) {
      return NextResponse.json(
        { error: manualSeoConflictError(candidate.seoSource) },
        { status: 409, headers: NO_STORE_HEADERS }
      )
    }

    return NextResponse.json(
      {
        ok: true,
        apply: true,
        seoTitle: generated.seoTitle,
        seoDescription: generated.seoDescription,
        seoSource: 'auto',
        seoGeneratedAt: generated.generatedAt.toISOString(),
        seoModel: generated.model || null,
        seoNeedsReview: true,
      },
      { headers: NO_STORE_HEADERS },
    )
  } catch (error) {
    if (error instanceof ProviderNotConfiguredError) {
      return NextResponse.json(
        { error: `Provider not configured: ${error.providerEnvVar}` },
        { status: 503, headers: NO_STORE_HEADERS }
      )
    }
    const message = error instanceof Error ? error.message : 'Failed to generate SEO metadata'
    return NextResponse.json({ error: message }, { status: 500, headers: NO_STORE_HEADERS })
  }
}
