// Legal page content for /privacy and /terms — migrated from the legacy CMS
// pages on 2026-08-24 (the catch-all Puck route never rendered them; these
// pathnames are reserved for hardcoded routes in SITE_PAGE_DEFS).

export type LegalSection = { id: string; title: string; body: string }

export type LegalPageContent = {
  badgeLabel: string
  title: string
  description: string
  sections: LegalSection[]
}

export const PRIVACY_PAGE: LegalPageContent = {
  badgeLabel: "Privacy Notice Overview",
  title: "Velvet Dinosaur - Privacy Notice",
  description: "",
  sections: [
    { id: "overview", title: "Privacy Notice Overview", body: "Last updated: 24 August 2026\nThis privacy notice tells you what to expect us to do with your personal information. It applies to visitors, prospective clients, and clients who interact with Velvet Dinosaur.\nKey points summary\n• We only collect information needed to deliver services, run the business, and meet legal duties.\n• We use trusted suppliers and share only what is necessary for them to provide their services.\n• We keep information for defined periods and delete it when it is no longer needed.\n• You have clear rights over your data, and we respond to requests within one month." },
    { id: "who-we-are", title: "Who We Are", body: "Velvet Dinosaur Web Design Ltd, trading as Velvet Dinosaur (\"Velvet Dinosaur\", \"we\", \"us\"), is the data controller for the personal information we hold. Registered in England and Wales.\nCompany number [NUMBER]\nRegistered office: [ADDRESS]\nTrading address\n16 Holloway Lane\nMinster Lovell\nWitney\nOxfordshire\nOX29 0AU" },
    { id: "contact-details", title: "Contact Details", body: "+44 7438 460437\nprivacy@velvetdinosaur.com" },
    { id: "personal-information", title: "Personal Information We Collect", body: "We collect or use personal information to provide our services, to run our business, and to meet legal obligations.\nInformation you provide\n• Names and contact details (for example, email address and telephone number).\n• Postal addresses (where needed for invoicing or contractual documents).\n• Business details (such as company name and role).\n• Enquiry and correspondence information (including emails and messages sent to us).\n• Purchase or service history (such as the services you have requested from us).\n• Content you provide to us for a project (for example, copy, images, and other materials).\n• If we accept card payments, payment-related information needed to take payment. We do not store full card details.\nInformation collected automatically\n• Website and technical data (such as IP address, device information, and server logs used for security and troubleshooting)." },
    { id: "why-we-use", title: "Why We Use Your Information", body: "We use personal information to provide our services, to run our business, and to meet legal obligations.\n• Responding to enquiries, providing quotes, and preparing proposals.\n• Delivering website projects and ongoing support.\n• Invoicing, payments, and accounting.\n• Managing our relationship with you, including communications and updates.\n• Maintaining security, preventing fraud, and troubleshooting technical issues.\n• Meeting legal, regulatory, and tax obligations." },
    { id: "lawful-bases", title: "Lawful Bases for Processing", body: "Under UK data protection law, we must have a lawful basis for collecting and using your personal information. Our lawful bases are:\n• Contract: to enter into or carry out a contract with you (for example, to deliver website services).\n• Legitimate interests: to run and improve our business (for example, responding to enquiries, preventing fraud, maintaining security, and improving our services).\n• Legal obligation: to comply with legal requirements (for example, keeping accounting records).\n• Consent: where you have given clear permission (for example, for marketing communications or optional cookies/analytics where used)." },
    { id: "data-rights", title: "Your Data Protection Rights", body: "Your data protection rights include the right of access, rectification, erasure, restriction, objection, and data portability. You also have rights in relation to automated decision-making and profiling.\nIf you make a request, we will respond without undue delay and in any event within one month." },
    { id: "sharing", title: "Who We Share Information With", body: "We use trusted suppliers (data processors) to help us deliver our services. Where we share data, we only share what is necessary and we require appropriate security measures.\nHosting & infrastructure (Hetzner)\nWe host our website and systems with Hetzner. This may involve processing names, contact details, and technical logs needed to operate and secure our services.\nBackups (Hetzner Storage Box)\nWe store encrypted backups using Hetzner Storage Box (or equivalent Hetzner backup storage).\nDomain registration & DNS (Spaceship)\nWe use Spaceship as our domain registrar (and, where applicable, DNS provider). This may involve processing domain registration details and contact information required to manage domains.\nEmail delivery & inbound processing (Postmark)\nWe use Postmark to send transactional emails (for example, form notifications) and to process inbound emails where this is part of the service provided. This may involve processing email content and metadata necessary to deliver and route messages.\nBusiness communications (WhatsApp)\nIf you contact us via WhatsApp, messages are processed by WhatsApp Ireland Limited and/or Meta Platforms as part of providing that service. Please avoid sharing sensitive information via WhatsApp.\nPayments (Stripe, if applicable)\nIf we accept card payments, payments are processed by Stripe. We do not store full card details. Stripe processes payment details on our behalf as a data processor. We share with Stripe the information needed to take payment (such as your name, email address, billing details, and transaction information).\nAnalytics (Google, if enabled)\nWe do not currently use analytics cookies. If we add analytics (such as Google Analytics) in future, we will update this notice and provide a cookie banner and choices to collect consent where required." },
    { id: "international-transfers", title: "International Transfers", body: "Some suppliers may process personal information outside the UK. Where this happens, we rely on appropriate safeguards such as UK adequacy regulations, the UK Extension to the EU-US Data Privacy Framework (where applicable), and/or standard contractual clauses." },
    { id: "information-sources", title: "Where We Get Personal Information From", body: "• Directly from you (for example, when you contact us, request a quote, or become a client).\n• From your use of our website and systems (for example, technical logs).\n• From our suppliers (for example, payment confirmation from a payment provider, or delivery metadata from an email provider)." },
    { id: "retention", title: "How Long We Keep Information", body: "We keep personal information only for as long as necessary for the purposes set out in this notice, to provide our service, and to meet legal, accounting, or reporting requirements.\nType of information | Typical retention period\nEnquiries and consultation requests | Up to 12 months\nClient project communications (email/phone/WhatsApp) | Up to 24 months after project completion\nClient project files and website content | For the duration of the service, and up to 12 months after the end of the contract (unless you request earlier deletion)\nBackups | Rolling backups retained for up to 30 days\nInvoices and accounting records | 6 years\nSecurity logs | Typically 30-90 days (unless needed to investigate an incident)" },
    { id: "complaints", title: "How to Complain", body: "If you have any concerns about our use of your personal information, you can make a complaint to us using the contact details above.\nIf you remain unhappy with how we have used your data after raising a complaint with us, you can also complain to the ICO.\nInformation Commissioner's Office\nWycliffe House\nWater Lane\nWilmslow\nCheshire\nSK9 5AF\nHelpline: 0303 123 1113\nWebsite: ico.org.uk" },
  ],
}

export const TERMS_PAGE: LegalPageContent = {
  badgeLabel: "Velvet Dinosaur",
  title: "Velvet Dinosaur – Terms of Service (Plain English)",
  description: "",
  sections: [
    { id: "overview", title: "Velvet Dinosaur – Terms of Service (Plain English)", body: "Last updated: 24 August 2026\nThese terms explain how Velvet Dinosaur provides website and related digital services. They are written in plain English to be easy to understand.\nIf anything in your proposal/statement of work (SOW) or signed contract differs from these terms, the proposal/SOW/contract will take precedence.\nKey points summary\n• We build bespoke websites and related digital services as agreed in a proposal/SOW.\n• A 50% deposit secures your project start date; the balance is due on delivery (unless your proposal says otherwise).\n• You own the final website deliverables once all invoices are paid.\n• Changes outside the agreed scope are quoted and approved before we start them.\nOverview\nVelvet Dinosaur provides bespoke website design and development services. We aim to make projects straightforward, reliable, and easy to maintain.\nThese terms apply to:\n• visitors who request a quote or consultation, and\n• clients who purchase services from us." },
    { id: "who-we-are", title: "Who we are", body: "Velvet Dinosaur Web Design Ltd, trading as Velvet Dinosaur (\"Velvet Dinosaur\", \"we\", \"us\"). Registered in England and Wales.\nCompany number [NUMBER]\nRegistered office: [ADDRESS]\nTrading address\n16 Holloway Lane\nMinster Lovell\nWitney\nOxfordshire\nOX29 0AU" },
    { id: "contact-details", title: "Contact details", body: "Phone: +44 7438 460437\nEmail: privacy@velvetdinosaur.com (or the email address used in your proposal)" },
    { id: "services", title: "Services", body: "Services may include (depending on what you purchase):\n• Website design and build\n• Copy support (if agreed)\n• Performance and accessibility improvements\n• SEO setup (foundational/on-page, if agreed)\n• Integrations (forms, email notifications, booking tools, etc.)\n• Hosting setup and ongoing support (if agreed)\nThe exact services, deliverables, and timeline will be set out in your proposal/SOW." },
    { id: "quotes-scope", title: "Quotes & scope", body: "Proposal / statement of work\nBefore starting, we will provide a proposal (or SOW) that should include:\n• scope and deliverables\n• assumptions and exclusions\n• timeline and milestones\n• total price and payment schedule\n• what we need from you (content, access, approvals)\nOut of scope work\nIf you ask for work outside the agreed scope, we will:\n• explain what’s out of scope,\n• provide a quote (or estimate) and impact on timeline,\n• start only after you approve in writing." },
    { id: "timelines", title: "Timelines & your responsibilities", body: "Timelines\nTimelines are based on:\n• timely access to systems (domain, hosting, CMS, analytics, etc.)\n• timely feedback and approvals\n• content provided when needed\nIf approvals or content are delayed, delivery dates may move.\nYour responsibilities\nYou agree to:\n• provide required access (logins, DNS/registrar access, existing assets)\n• provide content (text, images, branding) by agreed dates\n• review and approve work within a reasonable timeframe (typically 3–5 working days unless otherwise agreed)\n• ensure you have rights to use any content you supply\nProject dormancy (pauses)\nIf a project is paused for more than 30 days because we haven’t received content, access, feedback, or approvals from you, we may:\n• invoice for work completed to date, and\n• remove the project from our active schedule.\nRestarting the project may require re-scheduling based on our current availability, and (where appropriate) a restart fee. We’ll always discuss this with you before applying it." },
    { id: "payment-terms", title: "Payment terms", body: "We use a simple two-stage payment plan to keep things fair to both sides.\nDeposit\n• A 50% deposit is required to secure your start date.\n• Work begins once the deposit is received (unless otherwise agreed in writing).\nBalance on delivery (default)\nUnless your proposal/SOW states otherwise, the remaining 50% balance is due when the site is ready for launch/handover (before going live).\nFor larger projects, we may agree additional milestones in the proposal/SOW, but the default is a 50% deposit and 50% on delivery.\nInvoicing and due dates\n• Invoices are due within 7 days unless stated otherwise.\n• If payment is late, we may pause work until the account is up to date.\nExpenses and third-party costs\n• Third-party services (e.g., paid plugins, stock images, email providers, domain renewals) are either billed to you at cost or paid directly by you, as agreed.\n• We will always confirm costs before purchase.\nRefunds\n• The deposit is used to reserve time and begin work. If you cancel before work starts, we’ll refund it minus any reasonable admin costs. If work has started, the deposit is typically non-refundable because time will have been committed.\n• For cancellations after work begins, you pay for work completed up to that point (based on milestones or time/costs as agreed)." },
    { id: "revisions", title: "Revisions & change requests", body: "Included revisions\nYour proposal/SOW will specify what revisions are included. If it does not, we typically include:\n• a reasonable number of copy/layout tweaks during build, and\n• one structured review round on key pages.\nChange requests\nAnything outside included revisions or outside scope is treated as a change request:\n• we’ll quote it,\n• you approve it,\n• then we deliver it." },
    { id: "content", title: "Content (text, images, assets)", body: "• You are responsible for ensuring you have permission to use any content you provide.\n• If you want us to source stock imagery or write copy, this must be agreed in the proposal/SOW.\n• If content isn’t supplied on time, we may proceed with placeholders to keep the project moving." },
    { id: "launch-handover", title: "Launch & handover", body: "Testing and acceptance\nBefore launch, you’ll have an opportunity to review the site. Minor snags/bugs will be addressed as part of launch readiness.\nBrowser & device support\nWe test our work on current versions of major modern browsers (Chrome, Safari, Firefox and Edge) and on standard, widely used mobile devices.\nWe can’t guarantee pixel-perfect display on obsolete browsers (for example, Internet Explorer) or older devices that are no longer supported by their manufacturers. If you have a specific device or setup you need us to support, tell us at the start and we’ll confirm whether it’s included in scope.\nLaunch\nFinal payment (or the pre-launch milestone payment) must be received before the site goes live or before final deliverables are handed over, unless otherwise agreed.\nHandover\nOn completion, we will provide (as applicable):\n• admin access and instructions to edit your site\n• basic documentation (where agreed)\n• key credentials or a handover pack (where agreed)" },
    { id: "hosting-support", title: "Hosting, support & maintenance", body: "Hosting/support terms depend on what you buy.\n• If we provide hosting, it will be described in your proposal/SOW (including price and what’s included).\n• Support/maintenance is optional unless explicitly included in your plan.\nIf we arrange hosting for you, we are acting as an intermediary (we’re not a data centre). We can’t guarantee 100% uptime, but we only use reputable providers and will help you respond quickly if there’s an outage.\nIf your website relies on third-party services (email delivery, forms, analytics, etc.), those services may change their pricing or terms over time." },
    { id: "intellectual-property", title: "Intellectual property", body: "Your materials\nYou retain ownership of any content or assets you provide.\nOur work\nOnce all invoices are paid:\n• you own the final website deliverables created specifically for you (design and build work), except for\n• third-party components/tools and any pre-existing libraries/frameworks (which remain under their respective licences).\nPortfolio\nUnless you ask us not to, we may display the project (screenshots and a short description) in our portfolio. We won’t share private data or credentials." },
    { id: "third-party-services", title: "Third-party services", body: "We may recommend or integrate third-party services (e.g., hosting providers, email services, analytics tools). You agree that:\n• third-party services are governed by their own terms, and\n• we are not responsible for outages or changes to those services." },
    { id: "confidentiality", title: "Confidentiality", body: "Both sides agree to keep confidential information private, and only use it to deliver the project, unless disclosure is required by law." },
    { id: "liability", title: "Liability and warranties (plain English)", body: "We take care to deliver high-quality work, but no website can be guaranteed to be error-free forever.\nTo the extent permitted by law:\n• we are not liable for losses caused by factors outside our control (e.g., third-party outages, client-supplied content issues, platform changes)\n• we are not liable for indirect or consequential losses (like lost profits)\n• our total liability is limited to the fees you paid for the services giving rise to the claim, unless a higher limit is required by law\nNothing in these terms limits liability where it cannot be limited under law." },
    { id: "termination", title: "Termination", body: "Either party may end the agreement by written notice if:\n• the other party materially breaches these terms and does not remedy within a reasonable time, or\n• as otherwise specified in the proposal/SOW.\nIf terminated:\n• you pay for work completed up to termination,\n• we will provide what has been completed once outstanding invoices are settled." },
    { id: "governing-law", title: "Governing law", body: "These terms are governed by the laws of England and Wales, and disputes will be subject to the courts of England and Wales." },
    { id: "contact", title: "Contact", body: "If you have questions about these terms, contact:\nVelvet Dinosaur\n16 Holloway Lane, Minster Lovell, Witney, Oxfordshire, OX29 0AU\n+44 7438 460437\nprivacy@velvetdinosaur.com" },
  ],
}
