// Legal page content for /privacy and /terms — migrated from the legacy CMS
// pages on 2026-08-24 (the catch-all Puck route never rendered them; these
// pathnames are reserved for hardcoded routes in SITE_PAGE_DEFS).

export type LegalSection = { id: string; title: string; body: string }

export type LegalPageContent = {
  badgeLabel: string
  title: string
  description: string
  /** Optional link rendered after the sections (e.g. to the full agreement). */
  cta?: { href: string; label: string }
  sections: LegalSection[]
}

export const PRIVACY_PAGE: LegalPageContent = {
  badgeLabel: "Privacy Notice Overview",
  title: "Velvet Dinosaur - Privacy Notice",
  description: "",
  sections: [
    { id: "overview", title: "Privacy Notice Overview", body: "Last updated: 24 August 2026\nThis privacy notice tells you what to expect us to do with your personal information. It applies to visitors, prospective clients, and clients who interact with Velvet Dinosaur.\nKey points summary\n• We only collect information needed to deliver services, run the business, and meet legal duties.\n• We use trusted suppliers and share only what is necessary for them to provide their services.\n• We keep information for defined periods and delete it when it is no longer needed.\n• You have clear rights over your data, and we respond to requests within one month." },
    { id: "who-we-are", title: "Who We Are", body: "{{IDENTITY}}" },
    { id: "contact-details", title: "Contact Details", body: "General enquiries: hello@velvetdinosaur.com\nData protection: privacy@velvetdinosaur.com\nPhone: +44 7438 460437" },
    { id: "personal-information", title: "Personal Information We Collect", body: "We collect or use personal information to provide our services, to run our business, and to meet legal obligations.\nInformation you provide\n• Names and contact details (for example, email address and telephone number).\n• Postal addresses (where needed for invoicing or contractual documents).\n• Business details (such as company name and role).\n• Enquiry and correspondence information (including emails and messages sent to us).\n• Purchase or service history (such as the services you have requested from us).\n• Content you provide to us for a project (for example, copy, images, and other materials).\n• If we accept card payments, payment-related information needed to take payment. We do not store full card details.\nInformation collected automatically\n• Website and technical data (such as IP address, device information, and server logs used for security and troubleshooting)." },
    { id: "why-we-use", title: "Why We Use Your Information", body: "We use personal information to provide our services, to run our business, and to meet legal obligations.\n• Responding to enquiries, providing quotes, and preparing proposals.\n• Delivering website projects and ongoing support.\n• Invoicing, payments, and accounting.\n• Managing our relationship with you, including communications and updates.\n• Maintaining security, preventing fraud, and troubleshooting technical issues.\n• Meeting legal, regulatory, and tax obligations." },
    { id: "lawful-bases", title: "Lawful Bases for Processing", body: "Under UK data protection law, we must have a lawful basis for collecting and using your personal information. Our lawful bases are:\n• Contract: to enter into or carry out a contract with you (for example, to deliver website services).\n• Legitimate interests: to run and improve our business (for example, responding to enquiries, preventing fraud, maintaining security, and improving our services).\n• Legal obligation: to comply with legal requirements (for example, keeping accounting records).\n• Consent: where you have given clear permission (for example, for marketing communications or optional cookies/analytics where used)." },
    { id: "data-rights", title: "Your Data Protection Rights", body: "Your data protection rights include the right of access, rectification, erasure, restriction, objection, and data portability. You also have rights in relation to automated decision-making and profiling.\nIf you make a request, we will respond without undue delay and in any event within one month." },
    { id: "sharing", title: "Who We Share Information With", body: "We use trusted suppliers (data processors) to help us deliver our services. Where we share data, we only share what is necessary and we require appropriate security measures.\nHosting & infrastructure (Hetzner)\nWe host our website and systems with Hetzner. This may involve processing names, contact details, and technical logs needed to operate and secure our services.\nBackups (Hetzner Storage Box)\nWe store encrypted backups using Hetzner Storage Box (or equivalent Hetzner backup storage).\nDomain registration & DNS (Spaceship)\nWe use Spaceship as our domain registrar (and, where applicable, DNS provider). This may involve processing domain registration details and contact information required to manage domains.\nEmail delivery & inbound processing (Postmark)\nWe use Postmark to send transactional emails (for example, form notifications) and to process inbound emails where this is part of the service provided. This may involve processing email content and metadata necessary to deliver and route messages.\nBusiness communications (WhatsApp)\nIf you contact us via WhatsApp, messages are processed by WhatsApp Ireland Limited and/or Meta Platforms as part of providing that service. Please avoid sharing sensitive information via WhatsApp.\nPayments (Stripe, if applicable)\nIf we accept card payments, payments are processed by Stripe. We do not store full card details. Stripe processes payment details on our behalf as a data processor. We share with Stripe the information needed to take payment (such as your name, email address, billing details, and transaction information).\nAnalytics (Google, if enabled)\nWe do not currently use analytics cookies. If we add analytics (such as Google Analytics) in future, we will update this notice and provide a cookie banner and choices to collect consent where required." },
    { id: "international-transfers", title: "International Transfers", body: "Some suppliers may process personal information outside the UK. Where this happens, we rely on appropriate safeguards such as UK adequacy regulations, the UK Extension to the EU-US Data Privacy Framework (where applicable), and/or standard contractual clauses." },
    { id: "information-sources", title: "Where We Get Personal Information From", body: "• Directly from you (for example, when you contact us, request a quote, or become a client).\n• From your use of our website and systems (for example, technical logs).\n• From our suppliers (for example, payment confirmation from a payment provider, or delivery metadata from an email provider)." },
    { id: "retention", title: "How Long We Keep Information", body: "We keep personal information only for as long as necessary for the purposes set out in this notice, to provide our service, and to meet legal, accounting, or reporting requirements.\nType of information | Typical retention period\nEnquiries and consultation requests | Up to 12 months\nClient project communications (email/phone/WhatsApp) | Up to 24 months after project completion\nClient project files and website content | For the duration of the service, and up to 12 months after the end of the contract (unless you request earlier deletion)\nBackups | Rolling backups retained for up to 30 days\nInvoices and accounting records | 6 years\nSecurity logs | Typically 30-90 days (unless needed to investigate an incident)" },
    { id: "business-outreach", title: "Business-to-Business Outreach", body: "We sometimes approach organisations directly to introduce our services.\nWhere we get the details: professional contact information published on business websites, public directories, and similar publicly available business sources. We do not buy marketing lists of personal contact details.\nWhat we use: business names, business email addresses, business telephone numbers, and the address of the organisation's website. We use these only to make a relevant business-to-business approach about website design, hosting and maintenance.\nOur lawful basis: legitimate interests — promoting a small business to organisations we reasonably believe would benefit. We keep this proportionate: a small number of relevant approaches, never high-volume or automated bulk mailing.\nYour right to object: tell us to stop and we will, without argument. We record your details on a suppression list so you are not contacted again, and we keep only what is needed to honour that.\nTo object, or to ask what we hold, email privacy@velvetdinosaur.com." },
    { id: "complaints", title: "How to Complain", body: "If you have any concerns about our use of your personal information, you can make a complaint to us using the contact details above.\nIf you remain unhappy with how we have used your data after raising a complaint with us, you can also complain to the ICO.\nInformation Commissioner's Office\nWycliffe House\nWater Lane\nWilmslow\nCheshire\nSK9 5AF\nHelpline: 0303 123 1113\nWebsite: ico.org.uk" },
  ],
}

export const TERMS_PAGE: LegalPageContent = {
  badgeLabel: "Velvet Dinosaur",
  title: "Terms of Service",
  description: "",
  cta: { href: "/agreement", label: "Read the full Service Agreement →" },
  sections: [
    { id: "overview", title: "In one line", body: "Last updated: 25 August 2026\nOur websites are provided as a monthly managed service under the Velvet Dinosaur Service Agreement. That agreement — not this page — is the contract between us. This page summarises it and explains the rules for using this website." },
    { id: "who-we-are", title: "Who we are", body: "{{IDENTITY}}" },
    { id: "contact-details", title: "Contact details", body: "General enquiries: hello@velvetdinosaur.com\nData protection: privacy@velvetdinosaur.com\nPhone: +44 7438 460437" },
    { id: "the-service", title: "What you are buying", body: "A managed website service for £99 per month, payable monthly in advance.\nThere is no deposit, no setup fee and no website-build fee.\nWe build a working demonstration of your website before you pay anything, and you can try it free for 14 days.\nHosting, SSL, daily backups, security updates and reasonable support are included in the monthly price — they are not optional extras." },
    { id: "key-terms", title: "The key terms", body: "• The initial term is 12 months, then a rolling monthly service you can cancel with 30 days' notice.\n• Cancelling inside the initial term leaves the remaining months payable, in the same way as a broadband contract.\n• Your first 30 days as a paying subscriber are covered by our money-back guarantee.\n• Your domain, content and business data are yours. The Sauro platform and our software remain ours, licensed to you while you subscribe.\n• If you leave we help you migrate and provide an export of your content and data.\n• Routine content changes are included; anything chargeable is quoted and agreed with you first.\n• We will not increase your price during the initial term, and any later change needs 60 days' written notice." },
    { id: "full-agreement", title: "The full agreement", body: "The summary above is for convenience. The complete, binding terms are set out in the Velvet Dinosaur Service Agreement, which you read and accept before you subscribe. Where this page and the agreement differ, the agreement applies.\nYou can read it in full, or download it as a PDF, at velvetdinosaur.com/agreement." },
    { id: "using-this-website", title: "Using this website", body: "You are welcome to browse this website and to contact us through it.\nPlease do not misuse it: no attempts to gain unauthorised access, no automated scraping that degrades the service, and nothing unlawful.\nThe content, design and branding of this website belong to us. Client work shown in the portfolio is published with permission and remains the property of those clients.\nWe try to keep everything accurate and available, but we do not guarantee that the website will always be uninterrupted or error-free." },
    { id: "personal-data", title: "Your personal data", body: "How we handle personal information — including how we approach organisations about our services, and how to object — is explained in our Privacy Notice at velvetdinosaur.com/privacy." },
    { id: "governing-law", title: "Governing law", body: "These terms and the Service Agreement are governed by the laws of England and Wales, and disputes are subject to the courts of England and Wales. Before starting court proceedings, both sides agree to make reasonable efforts to resolve the matter directly." }
  ]
}
