import type { ThemeStatePayload } from 'tweakcn-ui';

// Static baseline theme payload (derived from `sanitizeThemePayload(null)`).
// Keeping this as plain data avoids calling into the theme sanitizer during
// prerender/static evaluation, which can trigger `Date.now()` warnings.
export const DEFAULT_THEME_PAYLOAD: ThemeStatePayload = {
  styles: {
    light: {
      background: 'oklch(1 0 0)',
      foreground: 'oklch(0.145 0 0)',
      card: 'oklch(1 0 0)',
      'card-foreground': 'oklch(0.145 0 0)',
      popover: 'oklch(1 0 0)',
      'popover-foreground': 'oklch(0.145 0 0)',
      primary: 'hsl(204 88% 53%)',
      'primary-foreground': 'hsl(0 0% 100%)',
      secondary: 'oklch(0.97 0 0)',
      'secondary-foreground': 'oklch(0.205 0 0)',
      muted: 'oklch(0.97 0 0)',
      'muted-foreground': 'oklch(0.556 0 0)',
      accent: 'oklch(0.97 0 0)',
      'accent-foreground': 'oklch(0.205 0 0)',
      destructive: 'oklch(0.577 0.245 27.325)',
      'destructive-foreground': 'oklch(1 0 0)',
      border: 'oklch(0.922 0 0)',
      input: 'oklch(0.922 0 0)',
      ring: 'hsl(204 88% 53%)',
      'chart-1': 'oklch(0.81 0.10 252)',
      'chart-2': 'oklch(0.62 0.19 260)',
      'chart-3': 'oklch(0.55 0.22 263)',
      'chart-4': 'oklch(0.49 0.22 264)',
      'chart-5': 'oklch(0.42 0.18 266)',
      radius: '0.625rem',
      sidebar: 'oklch(0.985 0 0)',
      'sidebar-foreground': 'oklch(0.145 0 0)',
      'sidebar-primary': 'hsl(204 88% 53%)',
      'sidebar-primary-foreground': 'hsl(0 0% 100%)',
      'sidebar-accent': 'oklch(0.97 0 0)',
      'sidebar-accent-foreground': 'oklch(0.205 0 0)',
      'sidebar-border': 'oklch(0.922 0 0)',
      'sidebar-ring': 'oklch(0.708 0 0)',
      'font-sans':
        "ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
      'font-serif': 'ui-serif, Georgia, Cambria, "Times New Roman", Times, serif',
      'font-mono':
        'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
      'shadow-color': 'oklch(0 0 0)',
      'shadow-opacity': '0.1',
      'shadow-blur': '3px',
      'shadow-spread': '0px',
      'shadow-offset-x': '0',
      'shadow-offset-y': '1px',
      'letter-spacing': '0em',
      spacing: '0.25rem',
      'typography-h1-base': '2.5rem',
      'typography-h1-md': '2.875rem',
      'typography-h1-lg': '3.25rem',
      'typography-h2-base': '2rem',
      'typography-h2-md': '2.25rem',
      'typography-h2-lg': '2.5rem',
      'typography-h3-base': '1.75rem',
      'typography-h3-md': '2rem',
      'typography-h3-lg': '2.25rem',
      'typography-h4-base': '1.5rem',
      'typography-h4-md': '1.625rem',
      'typography-h4-lg': '1.75rem',
      'typography-h5-base': '1.25rem',
      'typography-h5-md': '1.375rem',
      'typography-h5-lg': '1.5rem',
      'typography-h6-base': '1.125rem',
      'typography-h6-md': '1.25rem',
      'typography-h6-lg': '1.375rem',
      'typography-p-base': '1rem',
      'typography-p-md': '1.0625rem',
      'typography-p-lg': '1.125rem',
      'typography-span-base': '0.9375rem',
      'typography-span-md': '1rem',
      'typography-span-lg': '1.0625rem'
    },
    dark: {
      background: 'oklch(0.145 0 0)',
      foreground: 'oklch(0.985 0 0)',
      card: 'oklch(0.205 0 0)',
      'card-foreground': 'oklch(0.985 0 0)',
      popover: 'oklch(0.269 0 0)',
      'popover-foreground': 'oklch(0.985 0 0)',
      primary: 'hsl(204 88% 53%)',
      'primary-foreground': 'hsl(0 0% 100%)',
      secondary: 'oklch(0.269 0 0)',
      'secondary-foreground': 'oklch(0.985 0 0)',
      muted: 'oklch(0.269 0 0)',
      'muted-foreground': 'oklch(0.708 0 0)',
      accent: 'oklch(0.371 0 0)',
      'accent-foreground': 'oklch(0.985 0 0)',
      destructive: 'oklch(0.704 0.191 22.216)',
      'destructive-foreground': 'oklch(0.985 0 0)',
      border: 'oklch(0.275 0 0)',
      input: 'oklch(0.325 0 0)',
      ring: 'oklch(0.556 0 0)',
      'chart-1': 'oklch(0.81 0.10 252)',
      'chart-2': 'oklch(0.62 0.19 260)',
      'chart-3': 'oklch(0.55 0.22 263)',
      'chart-4': 'oklch(0.49 0.22 264)',
      'chart-5': 'oklch(0.42 0.18 266)',
      radius: '0.625rem',
      sidebar: 'oklch(0.205 0 0)',
      'sidebar-foreground': 'oklch(0.985 0 0)',
      'sidebar-primary': 'oklch(0.488 0.243 264.376)',
      'sidebar-primary-foreground': 'oklch(0.985 0 0)',
      'sidebar-accent': 'oklch(0.269 0 0)',
      'sidebar-accent-foreground': 'oklch(0.985 0 0)',
      'sidebar-border': 'oklch(0.275 0 0)',
      'sidebar-ring': 'oklch(0.439 0 0)',
      'font-sans':
        "ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
      'font-serif': 'ui-serif, Georgia, Cambria, "Times New Roman", Times, serif',
      'font-mono':
        'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
      'shadow-color': 'oklch(0 0 0)',
      'shadow-opacity': '0.1',
      'shadow-blur': '3px',
      'shadow-spread': '0px',
      'shadow-offset-x': '0',
      'shadow-offset-y': '1px',
      'letter-spacing': '0em',
      spacing: '0.25rem',
      'typography-h1-base': '2.5rem',
      'typography-h1-md': '2.875rem',
      'typography-h1-lg': '3.25rem',
      'typography-h2-base': '2rem',
      'typography-h2-md': '2.25rem',
      'typography-h2-lg': '2.5rem',
      'typography-h3-base': '1.75rem',
      'typography-h3-md': '2rem',
      'typography-h3-lg': '2.25rem',
      'typography-h4-base': '1.5rem',
      'typography-h4-md': '1.625rem',
      'typography-h4-lg': '1.75rem',
      'typography-h5-base': '1.25rem',
      'typography-h5-md': '1.375rem',
      'typography-h5-lg': '1.5rem',
      'typography-h6-base': '1.125rem',
      'typography-h6-md': '1.25rem',
      'typography-h6-lg': '1.375rem',
      'typography-p-base': '1rem',
      'typography-p-md': '1.0625rem',
      'typography-p-lg': '1.125rem',
      'typography-span-base': '0.9375rem',
      'typography-span-md': '1rem',
      'typography-span-lg': '1.0625rem'
    }
  },
  currentMode: 'light',
  fonts: [
    {
      role: 'sans',
      family: null,
      cssFamilyValue:
        "ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
      importUrl: null,
      defaultWeights: ['400'],
      isKnownNextGoogleFont: false
    },
    {
      role: 'serif',
      family: null,
      cssFamilyValue: 'ui-serif, Georgia, Cambria, "Times New Roman", Times, serif',
      importUrl: null,
      defaultWeights: ['400'],
      isKnownNextGoogleFont: false
    },
    {
      role: 'mono',
      family: null,
      cssFamilyValue:
        'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
      importUrl: null,
      defaultWeights: ['400'],
      isKnownNextGoogleFont: false
    }
  ],
  hslAdjustments: {
    hueShift: 0,
    saturationScale: 1,
    lightnessScale: 1
  }
};

