import { NextResponse } from 'next/server';
import { getAuth } from '@/lib/auth';
import { connectDB } from '@/lib/db';
import { Asset } from '@/models/Asset';
import { clamp01 } from '@/lib/media/focal-point';
import { getAltTextProviderInfo } from '@/lib/ai/alt-text-provider.server';
import { normalizeAssetTags } from '@/lib/assets/tags';
import { isImageUploadMime } from '@/lib/assets/image-variants';
import {
  computeAltForAsset,
  isImageAssetMime,
  persistAutoGeneratedAlt,
  shouldGenerateAltForAsset
} from '@/lib/assets/alt-text.server';

export async function POST(request: Request) {
  const auth = getAuth();
  const session = await auth.api.getSession({ headers: request.headers });
  if (!session) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  const body = await request.json();
  const hasTags = Object.prototype.hasOwnProperty.call(body ?? {}, 'tags');
  const key = body?.key;
  const etag = body?.etag;
  const size = body?.size;
  const mime = body?.mime;
  const folder = typeof body?.folder === 'string' && body.folder.trim() ? body.folder.trim() : undefined;
  const name = typeof body?.name === 'string' && body.name.trim() ? body.name.trim() : undefined;
  const caption =
    typeof body?.caption === 'string' && body.caption.trim() ? body.caption.trim() : undefined;
  const alt = typeof body?.alt === 'string' && body.alt.trim() ? body.alt.trim() : undefined;
  const focalX = clamp01(body?.focalX);
  const focalY = clamp01(body?.focalY);
  const width = typeof body?.width === 'number' && Number.isFinite(body.width) && body.width > 0 ? Math.round(body.width) : undefined;
  const height =
    typeof body?.height === 'number' && Number.isFinite(body.height) && body.height > 0 ? Math.round(body.height) : undefined;
  const tags = normalizeAssetTags(body?.tags);

  if (!key) {
    return NextResponse.json({ error: 'Missing key' }, { status: 400 });
  }
  if (isImageUploadMime(mime, key)) {
    return NextResponse.json(
      { error: 'Image uploads must be completed through server-side processing.' },
      { status: 400 }
    );
  }

  const bucket = process.env.R2_BUCKET || process.env.R2_BUCKET_NAME;
  if (!bucket) {
    return NextResponse.json({ error: 'R2_BUCKET not set' }, { status: 500 });
  }

  const conn = await connectDB();
  if (!conn) {
    return NextResponse.json({ error: 'Database unavailable' }, { status: 500 });
  }
  const update: Record<string, unknown> = {
    key,
    bucket,
    etag,
    size,
    mime,
    originalMime: mime,
    originalSize: size,
    optimizedSize: size,
    processingStatus: 'passthrough',
    processedAt: new Date(),
    fallbackKey: key
  };
  if (folder) update.folder = folder;
  if (name) update.name = name;
  if (caption) update.caption = caption;
  if (alt) update.alt = alt;
  if (alt) {
    update.altSource = 'manual';
    update.altNeedsReview = false;
    update.altGeneratedAt = null;
    update.altModel = null;
  }
  if (hasTags) update.tags = tags;
  if (width) update.width = width;
  if (height) update.height = height;
  if (focalX !== undefined) {
    update.focalX = focalX;
    update.focalSetAt = new Date();
    update.focalSetBy = session?.user?.id || 'system';
  }
  if (focalY !== undefined) {
    update.focalY = focalY;
    update.focalSetAt = new Date();
    update.focalSetBy = session?.user?.id || 'system';
  }
  await Asset.findOneAndUpdate({ key }, update, { upsert: true, new: true });

  const generationCandidate = {
    key,
    alt: typeof update.alt === 'string' ? update.alt : undefined,
    altSource: typeof update.altSource === 'string' ? (update.altSource as 'manual' | 'auto') : null,
    mime,
    width,
    height
  };
  if (isImageAssetMime(mime) && shouldGenerateAltForAsset(generationCandidate, { force: false })) {
    const provider = getAltTextProviderInfo();
    if (provider.configured) {
      computeAltForAsset(generationCandidate, request.url, { timeoutMs: 5000 })
        .then((computed) => {
          if (!computed) return;
          return persistAutoGeneratedAlt(key, computed, { needsReview: true });
        })
        .catch(() => {
          // keep upload completion resilient; alt generation can fail independently
        });
    }
  }

  return NextResponse.json({ ok: true });
}
