import { NextResponse } from 'next/server';
import { v4 as uuidv4 } from 'uuid';
import { getAuth } from '@/lib/auth';
import { getR2Client } from '@/lib/r2';
import { connectDB } from '@/lib/db';
import { Asset } from '@/models/Asset';
import { clamp01 } from '@/lib/media/focal-point';
import { getAltTextProviderInfo } from '@/lib/ai/alt-text-provider.server';
import { normalizeAssetTags } from '@/lib/assets/tags';
import {
  computeAltForAsset,
  isImageAssetMime,
  persistAutoGeneratedAlt,
  shouldGenerateAltForAsset
} from '@/lib/assets/alt-text.server';
import { storeAssetWithVariants } from '@/lib/assets/image-pipeline.server';
import { getOriginalExtension, getPublicExtensionForUpload } from '@/lib/assets/image-variants';

function stripExtension(filename: string) {
  if (!filename) return 'upload';
  return filename.replace(/\.[^/.]+$/, '');
}

function slugifyName(value: string) {
  const trimmed = value.trim().toLowerCase();
  if (!trimmed) return 'upload';
  const slug = trimmed.replace(/[^a-z0-9]+/g, '-').replace(/(^-+|-+$)/g, '');
  return slug || 'upload';
}

function normalizeFolderPath(input: unknown) {
  if (typeof input !== 'string') return '';
  const raw = input.trim().replace(/\\/g, '/');
  if (!raw) return '';
  const parts = raw
    .split('/')
    .map((part) => slugifyName(part))
    .filter(Boolean);
  return parts.join('/');
}

function parsePositiveInt(input: unknown) {
  if (typeof input !== 'string') return undefined;
  const parsed = Number(input);
  if (!Number.isFinite(parsed)) return undefined;
  const rounded = Math.round(parsed);
  if (rounded <= 0) return undefined;
  return rounded;
}

export async function POST(request: Request) {
  try {
    const auth = getAuth();
    const session = await auth.api.getSession({ headers: request.headers });
    if (!session) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const bucket = process.env.R2_BUCKET || process.env.R2_BUCKET_NAME;
    if (!bucket) {
      return NextResponse.json({ error: 'R2_BUCKET not set' }, { status: 500 });
    }

    const formData = await request.formData();
    const file = formData.get('file');
    if (!(file instanceof File)) {
      return NextResponse.json({ error: 'Missing file' }, { status: 400 });
    }

    const rawName = formData.get('name');
    const rawCaption = formData.get('caption');
    const rawAlt = formData.get('alt');
    const rawFolder = formData.get('folder');
    const rawWidth = formData.get('width');
    const rawHeight = formData.get('height');
    const rawFocalX = formData.get('focalX');
    const rawFocalY = formData.get('focalY');
    const rawTags = formData.get('tags');
    const fallbackName = stripExtension(file.name || 'upload');
    const name =
      typeof rawName === 'string' && rawName.trim() ? rawName.trim() : fallbackName;
    const caption =
      typeof rawCaption === 'string' && rawCaption.trim() ? rawCaption.trim() : undefined;
    const alt = typeof rawAlt === 'string' && rawAlt.trim() ? rawAlt.trim() : undefined;
    const folder = normalizeFolderPath(rawFolder) || undefined;
    const width = parsePositiveInt(rawWidth);
    const height = parsePositiveInt(rawHeight);
    const focalX = clamp01(rawFocalX);
    const focalY = clamp01(rawFocalY);
    const tags = normalizeAssetTags(rawTags);

    const uploadId = uuidv4();
    const keyBase = slugifyName(name);
    const folderPrefix = folder ? `${folder}/` : '';
    const contentType = file.type || 'application/octet-stream';
    const originalExtension = getOriginalExtension(file.name || '', contentType);
    const publicExtension = getPublicExtensionForUpload(file.name || '', contentType);
    const key = `uploads/${folderPrefix}${keyBase}-${uploadId}.${publicExtension}`;
    const originalKey = `asset-originals/${folderPrefix}${keyBase}-${uploadId}.${originalExtension}`;
    const body = Buffer.from(await file.arrayBuffer());

    const client = getR2Client();
    const stored = await storeAssetWithVariants({
      client,
      bucket,
      publicKey: key,
      originalKey,
      body,
      contentType
    });

    const conn = await connectDB();
    if (!conn) {
      return NextResponse.json({ error: 'Database unavailable' }, { status: 500 });
    }
    const storedWidth = width ?? stored.width;
    const storedHeight = height ?? stored.height;
    const update: Record<string, unknown> = {
      key: stored.key,
      bucket,
      originalKey: stored.originalKey,
      originalMime: stored.originalMime,
      originalSize: stored.originalSize,
      optimizedSize: stored.optimizedSize,
      processingStatus: stored.processingStatus,
      processedAt: stored.processedAt,
      fallbackKey: stored.fallbackKey,
      variants: stored.variants,
      etag: stored.etag,
      size: stored.size,
      mime: stored.mime,
      folder,
      name,
      caption,
      alt,
      tags,
      width: storedWidth,
      height: storedHeight
    };
    if (focalX !== undefined) {
      update.focalX = focalX;
      update.focalSetAt = new Date();
      update.focalSetBy = session?.user?.id || 'system';
    }
    if (focalY !== undefined) {
      update.focalY = focalY;
      update.focalSetAt = new Date();
      update.focalSetBy = session?.user?.id || 'system';
    }
    if (alt) {
      update.altSource = 'manual';
      update.altNeedsReview = false;
      update.altGeneratedAt = null;
      update.altModel = null;
    }
    await Asset.findOneAndUpdate({ key }, update, { upsert: true, new: true });

    const generationCandidate = {
      key: stored.key,
      alt: alt,
      altSource: typeof update.altSource === 'string' ? (update.altSource as 'manual' | 'auto') : undefined,
      mime: stored.mime,
      width: storedWidth,
      height: storedHeight
    };
    if (isImageAssetMime(stored.mime) && shouldGenerateAltForAsset(generationCandidate)) {
      const provider = getAltTextProviderInfo();
      if (provider.configured) {
        computeAltForAsset(
          generationCandidate,
          request.url,
          { timeoutMs: 5000 }
        )
          .then((generated) => {
            if (!generated) return;
            return persistAutoGeneratedAlt(stored.key, generated);
          })
          .catch(() => {
            // best-effort: never block upload completion
          });
      }
    }

    return NextResponse.json({
      key: stored.key,
      url: `/api/assets/file?key=${encodeURIComponent(stored.key)}`,
      name,
      caption,
      alt,
      tags,
      altSource: alt ? 'manual' : undefined,
      altGeneratedAt: undefined,
      altModel: undefined,
      altNeedsReview: alt ? false : undefined,
      focalX,
      focalY,
      width: storedWidth,
      height: storedHeight,
      folder,
      originalKey: stored.originalKey,
      originalMime: stored.originalMime,
      originalSize: stored.originalSize,
      optimizedSize: stored.optimizedSize,
      processingStatus: stored.processingStatus,
      processedAt: stored.processedAt,
      fallbackKey: stored.fallbackKey,
      variants: stored.variants
    });
  } catch (error) {
    const rawCode =
      typeof error === 'object' && error !== null
        ? ((error as { Code?: unknown; code?: unknown; name?: unknown }).Code ??
            (error as { code?: unknown }).code ??
            (error as { name?: unknown }).name)
        : undefined;
    const code = typeof rawCode === 'string' ? rawCode : undefined;
    const message = error instanceof Error ? error.message : 'Upload failed';
    if (code === 'AccessDenied') {
      return NextResponse.json(
        { error: 'R2 access denied. Check R2 credentials/bucket permissions.' },
        { status: 403 }
      );
    }
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
