import { Asset } from '@/models/Asset';
import {
  generateAltTextFromImageUrl,
  getAltTextProviderInfo
} from '@/lib/ai/alt-text-provider.server';

export type AltTextGenerationOptions = {
  timeoutMs?: number;
};

export type AltTextGenerationAsset = {
  key: string;
  alt?: string | null;
  altSource?: 'manual' | 'auto' | null;
  mime?: string | null;
  width?: number | null;
  height?: number | null;
};

export type AltTextGenerationResult = {
  alt: string;
  model?: string | null;
  generatedAt: Date;
};

const ALT_TEXT_MIN_WORDS = 5;
const ALT_TEXT_MAX_WORDS = 20;
const ALT_TEXT_FALLBACK = 'Photograph showing the image content.';

function readSafeRequestUrl(input: string) {
  if (typeof input !== 'string' || !input) return 'http://localhost';
  return input;
}

function clampWords(input: string, maxWords: number) {
  const words = input.split(/\s+/).filter(Boolean);
  if (words.length <= maxWords) return input;
  return words.slice(0, maxWords).join(' ');
}

function ensureMinimumWords(input: string) {
  const words = input.split(/\s+/).filter(Boolean);
  if (words.length >= ALT_TEXT_MIN_WORDS) return input;
  return `Detailed view of ${input.replace(/^a[n]? /i, '')}`.trim();
}

function stripLeadingIntroPhrases(input: string) {
  return input
    .replace(/^\s*(a|an|the)\s+(?:image|photo|photograph|picture)\s+(?:of|showing|depicting)\s+/i, '')
    .replace(/^\s*(?:image|photo|photograph|picture)\s+(?:of|showing|depicting)\s+/i, '')
    .trim();
}

function replaceSensitiveGuesses(input: string) {
  return input
    .replace(/\byoung|younger|older|elderly|child|children\b/gi, 'person')
    .replace(/\bblack|white|asian|hispanic|latino|disabled|blind|deaf\b/gi, 'person');
}

export function resolveAssetImageUrl(key: string, requestUrl: string) {
  const base = readSafeRequestUrl(requestUrl);
  return new URL(`/api/assets/file?key=${encodeURIComponent(key)}`, base).toString();
}

export function isImageAssetMime(mime?: string | null) {
  return typeof mime === 'string' && mime.startsWith('image/');
}

export function shouldGenerateAltForAsset(asset: AltTextGenerationAsset, options?: { force?: boolean }) {
  if (!asset || typeof asset.key !== 'string' || !asset.key.trim()) {
    return false;
  }
  if (!isImageAssetMime(asset.mime)) {
    return false;
  }

  if (asset.altSource === 'manual') {
    return false;
  }

  const altText = typeof asset.alt === 'string' ? asset.alt.trim() : '';
  if (altText) {
    return Boolean(options?.force);
  }
  return true;
}

export function postProcessAltText(input: string) {
  if (typeof input !== 'string') return ALT_TEXT_FALLBACK;
  const normalized = input
    .replace(/[\n\r\t]+/g, ' ')
    .replace(/^\s+|\s+$/g, '')
    .replace(/^(\"|')|(\"|')$/g, '')
    .replace(/\s+/g, ' ')
    .trim();

  const withoutLeadingPhrases = stripLeadingIntroPhrases(normalized);
  const withoutSensitiveGuesses = replaceSensitiveGuesses(withoutLeadingPhrases);
  const clamped = clampWords(withoutSensitiveGuesses, ALT_TEXT_MAX_WORDS).trim();
  const minApplied = ensureMinimumWords(clamped || ALT_TEXT_FALLBACK);
  return minApplied.replace(/\.$/, '').trim();
}

export async function computeAltForAsset(
  asset: AltTextGenerationAsset,
  requestUrl: string,
  options: AltTextGenerationOptions = {}
) {
  if (!shouldGenerateAltForAsset(asset)) {
    return null;
  }

  const altImageUrl = resolveAssetImageUrl(asset.key, requestUrl);
  const providerResult = await generateAltTextFromImageUrl(
    {
      url: altImageUrl,
      mime: asset.mime,
      width: asset.width,
      height: asset.height
    },
    { timeoutMs: options.timeoutMs }
  );

  return {
    alt: postProcessAltText(providerResult.alt),
    model: providerResult.model,
    generatedAt: new Date()
  };
}

export async function persistAutoGeneratedAlt(
  key: string,
  generated: AltTextGenerationResult,
  options?: { needsReview?: boolean }
) {
  await Asset.findOneAndUpdate(
    {
      key,
      $or: [{ altSource: { $ne: 'manual' } }, { altSource: { $exists: false } }, { altSource: null }]
    },
    {
      alt: generated.alt,
      altSource: 'auto',
      altGeneratedAt: generated.generatedAt,
      altModel: generated.model || null,
      altNeedsReview: options?.needsReview !== false
    },
    { upsert: true }
  ).exec();
}

export function getAltTextProviderCapability() {
  return getAltTextProviderInfo();
}
